# -*- coding: utf-8 -*-
"""fine_tune.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IO8cwisdj_1nRUcy2yVbSC8Y9rZUawf1
"""

!pip install -q vllm "bitsandbytes>=0.48.1" "antlr4-python3-runtime==4.11.1"
!pip install -U -q \
    "transformers>=4.51" \
    "trl>=0.13" \
    "peft>=0.13" \
    "datasets>=2.20" \
    "accelerate>=0.34"
# !pip install -q flash-attn --no-build-isolation

from google.colab import drive
drive.mount('/content/drive')

# Commented out IPython magic to ensure Python compatibility.
!unzip -q "/content/drive/MyDrive/CSE 151B/151B_SP26_Competition_dsv4_data.zip" -d /content/
!ls /content/151B_SP26_Competition
# %cd /content/151B_SP26_Competition

!nvidia-smi

import os
import torch

os.environ["PYTORCH_CUDA_ALLOC_CONF"] = "expandable_segments:True"
# ── Student model ──────────────────────────────────────────────────────────
MODEL_ID = "Qwen/Qwen3-4B-Thinking-2507"

# ── Data / output ──────────────────────────────────────────────────────────
DATA_PATH = "deepseekv4-pro/sft_data.jsonl"     # produced by get_data.py
OUT_DIR   = "deepseekv4-pro/qwen3-4b-sft-lora"  # LoRA adapter saved here

# ── Training knobs ─────────────────────────────────────────────────────────
MAX_LEN    = 40000   # examples LONGER than this are dropped (not truncated)
EPOCHS     = 3       # 2-3 is right for ~1-2k examples; watch for overfitting
LR         = 2e-4
LORA_R     = 16      # must match max_lora_rank in your vLLM serving config
GRAD_ACCUM = 16      # effective batch = 1 × GRAD_ACCUM = 16

# Set to "flash_attention_2" only if flash-attn installed successfully
os.makedirs(OUT_DIR, exist_ok=True)
print(f"GPU: {torch.cuda.get_device_name(0)}")
print("Config loaded.")

from transformers import AutoTokenizer

tok = AutoTokenizer.from_pretrained(MODEL_ID, trust_remote_code=True)

# Qwen3 tokenizer already has a pad token, but set a fallback just in case.
if tok.pad_token is None:
    tok.pad_token = tok.eos_token

print(f"Vocab size : {tok.vocab_size}")
print(f"EOS token  : {tok.eos_token!r}  (id={tok.eos_token_id})")
print(f"PAD token  : {tok.pad_token!r}  (id={tok.pad_token_id})")

import torch
from transformers import AutoModelForCausalLM, BitsAndBytesConfig

bnb_cfg = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.bfloat16,
    bnb_4bit_use_double_quant=True,      # saves ~0.4 GB extra
)

model = AutoModelForCausalLM.from_pretrained(
    MODEL_ID,
    quantization_config=bnb_cfg,
    dtype=torch.bfloat16,                # fixed: was deprecated torch_dtype=
    device_map={"": 0},                  # single GPU
    trust_remote_code=True,
    attn_implementation="sdpa",  # H100: ~2× faster than sdpa

)
model.config.use_cache = False           # required with gradient checkpointing

print(f"Model loaded on: {next(model.parameters()).device}")
print(f"Param dtype    : {next(model.parameters()).dtype}")

print(model.config.max_position_embeddings)

from peft import LoraConfig

peft_cfg = LoraConfig(
    r=LORA_R,
    lora_alpha=2 * LORA_R,              # standard 2× rule
    lora_dropout=0.05,
    bias="none",
    task_type="CAUSAL_LM",
    # All seven projection matrices — covers attention + MLP
    target_modules=[
        "q_proj", "k_proj", "v_proj", "o_proj",
        "gate_proj", "up_proj", "down_proj",
    ],
)
print("LoRA config ready.")
print(f"  rank={LORA_R}, alpha={2*LORA_R}, dropout=0.05")

import sys
from datasets import load_dataset

if not os.path.exists(DATA_PATH):
    sys.exit(f"[error] {DATA_PATH} not found — run get_data.py first.")

ds = load_dataset("json", data_files=DATA_PATH, split="train")
print(f"Raw examples: {len(ds)}")

def render(ex):
    """Apply Qwen3's chat template to produce the training string.

    Key flags:
      add_generation_prompt=False  — we're formatting completed training
                                     examples, not open-ended prompts.
      enable_thinking=True         — ensures <think>/<think> are treated as
                                     special control tokens so the model learns
                                     the thinking format, not raw HTML-like text.
    """
    return {
        "text": tok.apply_chat_template(
            ex["messages"],
            tokenize=False,
            add_generation_prompt=False,
            enable_thinking=True,
        )
    }

ds = ds.map(render, remove_columns=ds.column_names)

# Drop over-length examples instead of truncating — a truncated assistant
# turn would teach the model an answer with no \boxed{}.
before = len(ds)
ds = ds.filter(lambda ex: len(tok(ex["text"]).input_ids) <= MAX_LEN)
print(f"After length filter: {len(ds)}/{before} examples fit within {MAX_LEN} tokens")

# ── Sanity-check: verify <think> tags and system prompt are present ──────
print("\n--- First rendered example (first 1000 chars) ---")
print(ds[0]["text"][:1000])
print("--- (truncated) ---\n")

from trl import SFTConfig, SFTTrainer
steps_per_epoch = len(ds) // GRAD_ACCUM
total_steps     = steps_per_epoch * EPOCHS
warmup_steps    = max(1, round(total_steps * 0.03))
print(f"~{steps_per_epoch} optimizer steps per epoch, {total_steps} total, {warmup_steps} warmup")
sft_cfg = SFTConfig(
    output_dir=OUT_DIR,
    dataset_text_field="text",
    max_length=MAX_LEN,
    packing=False,                       # don't pack: reasoning traces vary wildly in length

    # Epochs / batch
    num_train_epochs=EPOCHS,
    per_device_train_batch_size=1,
    gradient_accumulation_steps=GRAD_ACCUM,

    # Memory
    gradient_checkpointing=True,
    gradient_checkpointing_kwargs={"use_reentrant": False},
    bf16=True,
    optim="paged_adamw_8bit",

    # LR schedule
    learning_rate=LR,
    lr_scheduler_type="cosine",
    warmup_steps=warmup_steps,

    # Logging / saving
    logging_steps=16,
    save_strategy="epoch",
    report_to="none",
)

trainer = SFTTrainer(
    model=model,
    args=sft_cfg,
    train_dataset=ds,
    peft_config=peft_cfg,
    processing_class=tok,   # TRL <0.12: use  tokenizer=tok  instead
)
torch.cuda.empty_cache()
trainer.train()

trainer.save_model(OUT_DIR)
tok.save_pretrained(OUT_DIR)
print(f"LoRA adapter saved to ./{OUT_DIR}/")

# Zip the whole folder (excludes any HF cache that might've ended up inside)
!cd /content && zip -rq 151B_SP26_Competition_dsv4_ft.zip 151B_SP26_Competition \
    -x "151B_SP26_Competition/__pycache__/*" \
       "151B_SP26_Competition/.ipynb_checkpoints/*"

# Copy zip to Drive

# Verify
!cp /content/151B_SP26_Competition_dsv4_ft.zip /content/drive/MyDrive/CSE\ 151B/
!ls -lh /content/drive/MyDrive/CSE\ 151B/151B_SP26_Competition_dsv4_ft.zip

