# -*- coding: utf-8 -*-
"""get_data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w2H4aRVg7Z8po9N28pql4J-4G2zmOEiW
"""

!pip install sympy antlr4-python3-runtime==4.11.1

from google.colab import drive
drive.mount('/content/drive')

# Commented out IPython magic to ensure Python compatibility.
!unzip -q "/content/drive/MyDrive/CSE 151B/151B_SP26_Competition_done2.zip" -d /content/
!ls /content/151B_SP26_Competition
# %cd /content/151B_SP26_Competition

# ─────────────────────────────────────────────────────────────────────────────
# CELL 1 — Imports
# Standard-library + third-party imports needed throughout the notebook.
# sympy is used for exact LaTeX → numerical evaluation;
# antlr4-python3-runtime==4.11.1 is required for sympy's LaTeX parser.
# ─────────────────────────────────────────────────────────────────────────────

import json
import os
import re
import sys
from collections import Counter
from typing import Optional
import sympy as sp
from sympy.parsing.latex import parse_latex

# ─────────────────────────────────────────────────────────────────────────────
# CELL 2 — Configuration
# Edit this cell to match your local file paths and filtering preferences.
#
# Key switches:
#   ONE_PER_QUESTION – deduplicate to one correct trace per question (smaller
#                      but more diverse dataset; set False for maximum data).
#   REQUIRE_FINISHED – drop responses that didn't finish (stop_reason != STOP).
#                      Truncated traces have no valid \boxed{} target for SFT.
#   N_DIGITS         – decimal precision used when numerifying boxed answers
#                      for the judger; must match the competition default (10).
# ─────────────────────────────────────────────────────────────────────────────

DEEPSEEK_PATH      = "/content/drive/MyDrive/CSE 151B/deepseek-v4-pro_all_1.jsonl"  # 2000 model responses
ANSWER_KEY_PATH  = "/content/151B_SP26_Competition/data/public.jsonl"                 # ground-truth answers + questions
JUDGER_DIR       = "/content/151B_SP26_Competition"                                 # folder containing judger.py
OUT_DIR    = "deepseekv4-pro"
OUT_SFT    = os.path.join(OUT_DIR, "sft_data.jsonl")       # Qwen3 training data
OUT_KEPT   = os.path.join(OUT_DIR, "kept_correct.jsonl")   # full records for inspection
OUT_REPORT = os.path.join(OUT_DIR, "grading_report.txt")   # counts & diagnostics
OUT_WRONG  = os.path.join(OUT_DIR, "kept_wrong.jsonl")   # incorrect responses for inspection

ONE_PER_QUESTION = False   # True  → at most one correct trace per question_id
                           # False → keep every correct attempt (more data)
REQUIRE_FINISHED = True    # drop responses whose stop_reason is not "STOP"

N_DIGITS   = 12            # decimal digits for numerification
WORK_PREC  = N_DIGITS + 6  # extra sympy working precision to avoid rounding

# Field-name candidates for auto-detecting columns in the answer key.
# Add synonyms here if your answer-key file uses different column names.
KEY_ID_FIELDS     = ["id", "question_id", "qid", "idx", "index"]
KEY_QUESTION_FLDS = ["question", "problem", "prompt", "text"]
KEY_OPTION_FIELDS = ["options", "choices", "option"]
KEY_ANSWER_FIELDS = ["answer", "gold", "label", "solution", "final_answer",
                     "correct", "gt", "ground_truth", "target"]

# ─────────────────────────────────────────────────────────────────────────────
# CELL 3 — Boxed-answer span finder and top-level comma splitter
#
# find_last_boxed_span():
#   Scans a response string and returns (start, end, content) for the LAST
#   \boxed{...} block, correctly handling nested braces and escaped characters.
#   Returns None if no complete \boxed{} is found.
#
# split_top_level_commas():
#   Splits a comma-separated string only at commas that are NOT inside braces.
#   Used to handle multi-answer boxes like \boxed{a, b, c}.
# ─────────────────────────────────────────────────────────────────────────────

def find_last_boxed_span(text: str):
    """Return (start, end, content) of the last complete \\boxed{...}, or None."""
    if not text:
        return None
    needle = r"\boxed"
    n, last, i = len(text), None, 0
    while True:
        idx = text.find(needle, i)
        if idx == -1:
            break
        j = idx + len(needle)
        while j < n and text[j].isspace():
            j += 1
        if j >= n or text[j] != "{":
            i = idx + len(needle)
            continue
        depth, k = 1, j + 1
        start_content = k
        while k < n and depth > 0:
            ch = text[k]
            if ch == "\\" and k + 1 < n:
                k += 2
                continue
            if ch == "{":
                depth += 1
            elif ch == "}":
                depth -= 1
                if depth == 0:
                    break
            k += 1
        if depth == 0:
            last = (idx, k + 1, text[start_content:k])
            i = k + 1
        else:
            i = idx + len(needle)
    return last


def split_top_level_commas(s: str):
    """Split on commas that are not inside any brace or paren level.
    Tracks both {} and () so that \left(...,... \right) is kept intact."""
    out, depth, start, i, n = [], 0, 0, 0, len(s)
    while i < n:
        ch = s[i]
        if ch == "\\" and i + 1 < n:
            i += 2
            continue
        if ch in "{(":
            depth += 1
        elif ch in "})":
            depth -= 1
        elif ch == "," and depth == 0:
            out.append(s[start:i])
            start = i + 1
        i += 1
    out.append(s[start:])
    return [p.strip() for p in out if p.strip() != ""]

def split_quoted_answers(content: str):
    """Split on commas OUTSIDE double quotes.
    Returns list of unquoted sub-answer strings, or None if no quotes found.

    "ans1","ans2"       -> ['ans1', 'ans2']
    "(-8,\\infty)"    -> ['(-8,\\infty)']   (comma inside quotes kept)
    "A,B,C","YES"       -> ['A,B,C', 'YES']
    no quotes here      -> None
    """
    content = content.strip()
    if '"' not in content:
        return None
    parts, current, in_quote = [], [], False
    for ch in content:
        if ch == '"':
            in_quote = not in_quote
        elif ch == ',' and not in_quote:
            part = ''.join(current).strip()
            if part:
                parts.append(part)
            current = []
        else:
            current.append(ch)
    part = ''.join(current).strip()
    if part:
        parts.append(part)
    return parts if parts else None


def compress_letter_list(s: str) -> str:
    """If s is comma-separated single letters like 'A, B, C', join to 'ABC'.
    Otherwise return s unchanged.
    Collapses multi-select MCQ answers written as 'A,B,C' into 'ABC'."""
    parts = [p.strip() for p in s.split(',')]
    if len(parts) > 1 and all(re.fullmatch(r'[A-Za-z]', p) for p in parts):
        return ''.join(p.upper() for p in parts)
    return s


def numerify_paren_list(s: str, n_digits: int = N_DIGITS) -> str:
    """Numerify a sub-answer that may be a parenthesised value list.
    Handles both bare '(val1, val2)' and LaTeX '\left(val1, val2\right)'.
    Each value inside is numerified independently.
    Otherwise passes the whole string to evaluate_piece()."""
    inner = s.strip()
    # Strip \left / \right wrappers so we can detect the '(' ... ')' structure.
    unwrapped = re.sub(r"\\left\s*", "", inner)
    unwrapped = re.sub(r"\\right\s*", "", unwrapped).strip()
    if unwrapped.startswith('(') and unwrapped.endswith(')'):
        inner_content = unwrapped[1:-1]
        parts = split_top_level_commas(inner_content)
        if len(parts) > 1:
            new_parts = [evaluate_piece(p, n_digits) for p in parts]
            return '(' + ', '.join(new_parts) + ')'
    return evaluate_piece(s, n_digits)

# ─────────────────────────────────────────────────────────────────────────────
# CELL 4 — LaTeX cleaning and numerical evaluation (numerification)
#
# _CLEANUPS / _clean_latex():
#   Strip LaTeX macros that confuse sympy (\dfrac → \frac, spacing commands,
#   \left / \right, etc.) before parsing.
#
# evaluate_piece():
#   Convert a single boxed sub-answer to an N-digit decimal string using
#   sympy's LaTeX parser (or sympify fallback). Plain integers and floats are
#   handled cheaply without sympy. Returns the original string if evaluation
#   fails so nothing is silently dropped.
#
# numerify_response():
#   Locate the LAST \boxed{} in a full response, split its comma-separated
#   parts, numerify each one, and splice the result back into the text.
#   The judger then compares these decimal strings to the gold answers.
#   NOTE: the ORIGINAL symbolic text (not the numerified version) is what
#   gets saved into the SFT dataset — numerification is grading-only.
# ─────────────────────────────────────────────────────────────────────────────

# Regex substitutions applied before feeding LaTeX to sympy.
_CLEANUPS = [
    (r"\\dfrac", r"\\frac"),
    (r"\\tfrac", r"\\frac"),
    (r"\\!",     ""),
    (r"\\,",     ""),
    (r"\\;",     ""),
    (r"\\ ",     ""),
    (r"\\\\ ",  " "),
    (r"\\left",  ""),
    (r"\\right", ""),
    (r"\\$",     ""),
    (r"\\%",     ""),    # strip LaTeX \% — the fraction already IS the percentage value
    (r"\\text\{([^}]*)\}", r"\1"),  # \text{C} → C
]

import math as _math

def _sub_stat_quantiles(s: str) -> str:
    """Pre-substitute statistical distribution quantiles with decimal values.

    Replaces tokens like z_{0.015}, chi^2_{0.01,1}, t_{0.025,10},
    F_{0.05,2,30} with their numeric values BEFORE passing to parse_latex,
    so that surrounding expressions (e.g. '26 - \frac{\sqrt{105}}{15} z_{0.015}')
    can be evaluated as a whole rather than failing on free symbols.

    Also handles t with fractional df: t_{0.025, \frac{num}{den}} (Welch's df).

    Requires scipy; silently skips if not installed.
    """
    try:
        from scipy import stats as _sc

        # z_{alpha}  →  norm.ppf(1-alpha)
        def _z(m):
            return str(_sc.norm.ppf(1 - float(m.group(1))))
        s = re.sub(r"\bz\s*_\{?\s*([0-9.]+)\s*\}?", _z, s)

        # chi^2_{alpha, df}  or  \chi^2_{alpha, df}
        # Note: include optional leading \ so \chi^2_{...} doesn't leave a stray \.
        def _chi2(m):
            return str(_sc.chi2.ppf(1 - float(m.group(1)), int(m.group(2))))
        s = re.sub(
            r"\\?chi\^?2\s*_\{?\s*([0-9.]+)\s*,\s*([0-9]+)\s*\}?",
            _chi2, s, flags=re.IGNORECASE,
        )

        # t_{alpha, \frac{num}{den}}  — Welch's df expressed as a fraction
        def _t_frac(m):
            alpha = float(m.group(1))
            df = float(m.group(2)) / float(m.group(3))
            return str(_sc.t.ppf(1 - alpha, df))
        s = re.sub(
            r"\bt\s*_\{?\s*([0-9.]+)\s*,\s*\\frac\{([0-9]+)\}\{([0-9]+)\}\s*\}?",
            _t_frac, s,
        )

        # t_{alpha, df}  — integer or decimal df
        def _t(m):
            return str(_sc.t.ppf(1 - float(m.group(1)), float(m.group(2))))
        s = re.sub(r"\bt\s*_\{?\s*([0-9.]+)\s*,\s*([0-9.]+)\s*\}?", _t, s)

        # F_{alpha, df1, df2}
        def _f(m):
            return str(_sc.f.ppf(1 - float(m.group(1)), int(m.group(2)), int(m.group(3))))
        s = re.sub(
            r"\bF\s*_\{?\s*([0-9.]+)\s*,\s*([0-9]+)\s*,\s*([0-9]+)\s*\}?", _f, s
        )

    except ImportError:
        pass
    return s
def _eval_cdf_expression(s: str, n_digits: int, _depth: int = 0):
    r"""Evaluate expressions containing \Phi, \Phi^{-1}, \Pr(T_n < x).

    \Phi(x)        → norm.cdf(evaluate(x))
    \Phi^{-1}(p)   → norm.ppf(evaluate(p))
    \Pr(T_n < x)   → t.cdf(evaluate(x), df=n)

    Called from evaluate_piece; _depth prevents infinite recursion.
    Returns decimal string, or None if no CDF pattern found.
    """
    if "\\Phi" not in s and "\\Pr" not in s:
        return None
    try:
        from scipy import stats as _sc

        def _inner(expr_str):
            """Evaluate a sub-expression, guarded against recursion."""
            if _depth >= 2:
                return None
            result = evaluate_piece(expr_str.strip(), n_digits, _depth + 1)
            try:
                return float(result)
            except (ValueError, TypeError):
                return None

        s_work = s

        # \Phi^{-1}(p) → norm.ppf(p)  [check before \Phi(x) to avoid partial match]
        def _phi_inv(m):
            v = _inner(m.group(1))
            return f"{_sc.norm.ppf(v):.{n_digits}f}" if v is not None else m.group(0)
        s_work = re.sub(r"\\Phi\s*\^\{-1\}\s*\(([^)]+)\)", _phi_inv, s_work)

        # \Phi(x) → norm.cdf(x)
        def _phi(m):
            v = _inner(m.group(1))
            return f"{_sc.norm.cdf(v):.{n_digits}f}" if v is not None else m.group(0)
        s_work = re.sub(r"\\Phi\s*\(([^)]+)\)", _phi, s_work)

        # \Pr(T_{n} < x) → t.cdf(x, df=n)
        def _pr_t(m):
            df_v = _inner(m.group(1))
            x_v  = _inner(m.group(2))
            if df_v is None or x_v is None:
                return m.group(0)
            return f"{_sc.t.cdf(x_v, df_v):.{n_digits}f}"
        s_work = re.sub(
            r"\\Pr\s*\(\s*T_\{?(\d+)\}?\s*<\s*([^)]+)\)", _pr_t, s_work
        )

        if s_work == s:
            return None  # nothing matched

        # Try to evaluate the residual arithmetic (e.g. "1 - 0.8605...")
        try:
            return f"{float(s_work):.{n_digits}f}"
        except ValueError:
            pass
        try:
            val = sp.N(sp.sympify(s_work), WORK_PREC)
            return _format_numeric(val, n_digits)
        except Exception:
            pass
        return s_work   # best-effort: return modified string

    except Exception:
        return None

def _clean_latex(s: str) -> str:
    """Apply _CLEANUPS and strip a leading '=' sign (e.g. '= 3/4' → '3/4')."""
    s = s.strip()
    # Convert degree notation to a radian DECIMAL wrapped in braces.
    # Using a plain decimal (not \pi/180) avoids introducing '*' which is
    # not valid LaTeX and causes parse_latex to fail.
    #   \tan 23^\circ   →  \tan {0.40142...}   (braces = grouped argument)
    #   \cos(67^\circ)  →  \cos({1.16937...})
    #   67°             →  {1.16937...}
    def _deg2rad(m):
        return "{" + str(_math.radians(float(m.group(1)))) + "}"
    # (?(2)\}) = closing brace only if group 2 captured the opening brace.
    # This prevents eating the '}' that closes a surrounding \frac{}{...} argument.
    s = re.sub(r"(\d+(?:\.\d+)?)\s*\^(\{)?\\circ(?(2)\})", _deg2rad, s)
    s = re.sub(r"(\d+(?:\.\d+)?)\s*°",                      _deg2rad, s)
    for pat, rep in _CLEANUPS:
        s = re.sub(pat, rep, s)
    return re.sub(r"^=\s*", "", s).strip()

def _format_numeric(val, n_digits: int) -> str:
    """Format a sympy numeric value as a decimal string.
    Handles real, complex, and infinite results.
      real:     '3.141592653590'
      complex:  '-1.000000000000+2.449489742783i'
      infinity: '\\infty' or '-\\infty'
    Raises TypeError if val still contains free symbols.
    """
    re_part, im_part = val.as_real_imag()
    re_f = float(re_part)
    im_f = float(im_part)
    if _math.isinf(re_f):
        return "\\infty" if re_f > 0 else "-\\infty"
    if abs(im_f) < 1e-12:          # effectively real
        return f"{re_f:.{n_digits}f}"
    sign = "+" if im_f >= 0 else ""
    return f"{re_f:.{n_digits}f}{sign}{im_f:.{n_digits}f}i"

def evaluate_piece(piece: str, n_digits: int = N_DIGITS, _depth: int = 0) -> str:
    p = (piece or "").strip()
    if not p:
        return p
    # Single capital letter → always an MCQ choice, never a math expression.
    # Must come before sympy parsing because sympy maps E → Euler's constant.
    if re.fullmatch(r"[A-Z]", p):
        return p
    if re.fullmatch(r"-?\d+", p):
        return p
    m = re.fullmatch(r"-?\d+\.\d+", p)
    if m:
        try:
            return f"{float(p):.{n_digits}f}"
        except Exception:
            pass
    s = _clean_latex(p)
    s = _sub_stat_quantiles(s)   # replace z_{α}, chi²_{α,df}, etc. with decimals

    # Handle \Phi, \Phi^{-1}, \Pr(T_n < x) expressions
    cdf_result = _eval_cdf_expression(s, n_digits, _depth)
    if cdf_result is not None:
        return cdf_result

    try:
        if parse_latex is None:
            raise RuntimeError("no latex parser")
        expr = parse_latex(s)
        # Equality like x = -1/2 → extract RHS
        if isinstance(expr, sp.Eq):
            expr = expr.rhs
        expr = expr.subs([
            (sp.Symbol('pi'), sp.pi),
            (sp.Symbol('e'),  sp.E),
            (sp.Symbol('i'),  sp.I),   # treat bare i as imaginary unit
        ])
        val = sp.N(expr, WORK_PREC)
        return _format_numeric(val, n_digits)
    except Exception as e:
        print(f"[parse_latex FAILED] input={s!r}  error={e}")
    try:
        fallback_s = s.replace("\\", "")
        expr = sp.sympify(fallback_s)
        val  = sp.N(expr, WORK_PREC)
        return _format_numeric(val, n_digits)
    except Exception as e:
        print(f"[sympify FAILED] input={fallback_s!r}  error={e}")

    # Fallback 3: scipy for statistical distribution quantiles.
    # Handles chi^2_{alpha,df}, t_{alpha,df}, F_{alpha,df1,df2}, z_{alpha}.
    # Only reached when both sympy paths failed, so false-positives on
    # ambiguous letters (t, z) are unlikely in practice.
    try:
        from scipy import stats as _scipy_stats

        # chi^2_{alpha, df}  or  chi2_{alpha, df}
        m = re.search(
            r"chi\^?2\s*_\{?\s*([0-9.]+)\s*,\s*([0-9]+)\s*\}?", p, re.IGNORECASE
        )
        if m:
            alpha, df = float(m.group(1)), int(m.group(2))
            val = _scipy_stats.chi2.ppf(1 - alpha, df)
            return f"{val:.{n_digits}f}"

        # F_{alpha, df1, df2}
        m = re.search(
            r"[Ff]\s*_\{?\s*([0-9.]+)\s*,\s*([0-9]+)\s*,\s*([0-9]+)\s*\}?", p
        )
        if m:
            alpha, df1, df2 = float(m.group(1)), int(m.group(2)), int(m.group(3))
            val = _scipy_stats.f.ppf(1 - alpha, df1, df2)
            return f"{val:.{n_digits}f}"

        # t_{alpha, df}
        m = re.search(
            r"\bt\s*_\{?\s*([0-9.]+)\s*,\s*([0-9]+)\s*\}?", p
        )
        if m:
            alpha, df = float(m.group(1)), int(m.group(2))
            val = _scipy_stats.t.ppf(1 - alpha, df)
            return f"{val:.{n_digits}f}"

        # z_{alpha}  or  z_alpha
        m = re.search(r"\bz\s*_\{?\s*([0-9.]+)\s*\}?", p)
        if m:
            alpha = float(m.group(1))
            val = _scipy_stats.norm.ppf(1 - alpha)
            return f"{val:.{n_digits}f}"

    except Exception as e:
        print(f"[scipy FAILED] input={p!r}  error={e}")

    return p

def numerify_response(text: str, n_digits: int = N_DIGITS) -> str:
    """Replace the content of the LAST \\boxed{} with numerically evaluated parts.

    Supports two formats:
    - Quoted (new):  \\boxed{"ans1","ans2"} — each sub-answer in double quotes;
      compress_letter_list() collapses 'A,B,C' -> 'ABC' within each part;
      numerify_paren_list() handles '(val1, val2)' multi-value answers.
    - Legacy:        \\boxed{a, b, c} — bare comma-separated sub-answers.
    """
    try:
        span = find_last_boxed_span(text)
        if span is None:
            return text
        start, end, content = span

        # New: quoted format
        quoted_parts = split_quoted_answers(content)
        if quoted_parts is not None:
            new_parts = []
            for p in quoted_parts:
                p = compress_letter_list(p)        # 'A,B,C' -> 'ABC'
                p = numerify_paren_list(p, n_digits)  # evaluate numeric pieces
                new_parts.append(p)
            new_box = "\\boxed{" + ",".join(f'"{p}"' for p in new_parts) + "}"
            return text[:start] + new_box + text[end:]

        # Legacy: bare comma-separated (or single \left(...\right) interval)
        parts = split_top_level_commas(content)
        if not parts:
            return text
        new_parts = [numerify_paren_list(p, n_digits) for p in parts]
        new_box = "\\boxed{" + ", ".join(new_parts) + "}"
        return text[:start] + new_box + text[end:]
    except Exception:
        return text

evaluate_piece(r'\frac{504}{11\pi}', 12)

# ─────────────────────────────────────────────────────────────────────────────
# CELL 5 — Answer extraction helpers
#
# extract_letter():
#   For MCQ responses: pull the single letter from \boxed{X}.
#   Falls back to scanning for the last bare capital letter in the text
#   (handles responses that omit the box but write the letter).
#
# extract_boxed():
#   Return the raw content string inside the last \boxed{} (symbolic, not
#   numerified). Used to record the SFT answer target.
# ─────────────────────────────────────────────────────────────────────────────

def extract_letter(text: str) -> str:
    """Extract the single capital letter from \\boxed{X}, or from bare text."""
    m = re.search(r"\\boxed\{([A-Za-z])\}", text or "")
    if m:
        return m.group(1).upper()
    # Fallback: last bare capital letter in the response
    matches = re.findall(r"\b([A-Z])\b", (text or "").upper())
    return matches[-1] if matches else ""


def extract_boxed(text: str) -> str:
    """Return raw content of the last \\boxed{...} (symbolic, not evaluated)."""
    span = find_last_boxed_span(text or "")
    return span[2] if span else ""

# ─────────────────────────────────────────────────────────────────────────────
# CELL 6 — Official competition judger setup and scoring wrappers
#
# get_judger():
#   Imports judger.Judger from the competition's starter-code directory.
#   Exits with a clear message if the import fails (most common cause:
#   not running from the right directory or missing dependency).
#
# score_mcq():
#   MCQ scoring — compare extract_letter(response) to the gold letter.
#   Identical to the notebook's score_mcq().
#
# judge_free():
#   Free-form scoring — calls judger.auto_judge() on the NUMERIFIED text
#   (not the raw symbolic response) against the gold answer list.
#   Identical to the notebook's auto_judge() call.
# ─────────────────────────────────────────────────────────────────────────────

def get_judger():
    """Import and instantiate the competition Judger (judger.py must be on sys.path)."""
    if JUDGER_DIR not in sys.path:
        sys.path.insert(0, JUDGER_DIR)
    try:
        from judger import Judger
    except Exception as e:
        sys.exit(
            f"[error] could not import judger.py ({type(e).__name__}: {e}).\n"
            "        Run this notebook from the competition starter-code "
            "directory, or set JUDGER_DIR to the folder holding judger.py."
        )
    return Judger(strict_extract=False)


def score_mcq(response: str, gold_letter: str) -> bool:
    """MCQ: True iff the extracted letter matches the gold letter (case-insensitive)."""
    return extract_letter(response) == str(gold_letter).strip().upper()


def judge_free(judger, numerified_text: str, gold) -> bool:
    """Free-form: True iff judger.auto_judge() accepts the numerified answer.

    For quoted-format responses (\\boxed{"ans1","ans2"}), the quotes are
    stripped and the parts are rejoined bare so that auto_judge()'s own
    split_by_comma() handles boundary detection — it tracks () brackets, so
    commas inside intervals like (-8,inf) are safe.

    Falls back to passing the text unchanged for legacy bare-comma responses.
    """
    gold_list = gold if isinstance(gold, list) else [gold]

    # Quoted format: strip quotes and reconstruct bare boxed for auto_judge
    span = find_last_boxed_span(numerified_text)
    if span is not None:
        start, end, content = span
        quoted_parts = split_quoted_answers(content)
        if quoted_parts is not None:
            new_box = "\\boxed{" + ",".join(quoted_parts) + "}"
            numerified_text = numerified_text[:start] + new_box + numerified_text[end:]

    try:
        return bool(judger.auto_judge(
            pred=numerified_text,
            gold=gold_list,
            options=[[]] * len(gold_list),
        ))
    except Exception:
        return False

# ─────────────────────────────────────────────────────────────────────────────
# CELL 7 — Answer key loader
#
# _detect_field():
#   Scans ALL rows of the answer key to find which column name is in use
#   from a priority list of candidates. Scanning all rows (not just row 0)
#   is important because optional fields (e.g. 'options') are absent from
#   free-form rows and would be missed by a single-row probe.
#
# load_answer_key():
#   Reads the public JSONL file into a dict keyed by question_id.
#   Each entry stores the question text, options (if MCQ), gold answer,
#   and an is_mcq flag. Handles both list and string gold answers.
# ─────────────────────────────────────────────────────────────────────────────

def _detect_field(rows: list, candidates, required=True, what=""):
    """Return the first candidate column name found in any row, or exit."""
    for c in candidates:
        if any(isinstance(r, dict) and c in r for r in rows):
            return c
    if required:
        all_keys = sorted({k for r in rows for k in r.keys()})
        sys.exit(
            f"[error] could not find the {what} field in the answer key. "
            f"Keys present: {all_keys}. "
            f"Add the right name to the KEY_*_FIELDS list in the Config cell."
        )
    return None


def load_answer_key(path: str) -> dict:
    """Load and index the ground-truth answer key from a JSONL file."""
    if not os.path.exists(path):
        sys.exit(
            f"[error] ANSWER_KEY_PATH not found: {path}\n"
            f"        Edit ANSWER_KEY_PATH in the Config cell."
        )
    rows = [json.loads(l) for l in open(path, encoding="utf-8") if l.strip()]
    if not rows:
        sys.exit(f"[error] answer key is empty: {path}")

    # Auto-detect column names from the priority lists defined in Config
    f_id  = _detect_field(rows, KEY_ID_FIELDS,     True,  "question-id")
    f_q   = _detect_field(rows, KEY_QUESTION_FLDS, True,  "question-text")
    f_ans = _detect_field(rows, KEY_ANSWER_FIELDS, True,  "answer")
    f_opt = _detect_field(rows, KEY_OPTION_FIELDS, False, "options")
    print(f"[answer key] id='{f_id}'  question='{f_q}'  "
          f"answer='{f_ans}'  options='{f_opt}'")

    key = {}
    for r in rows:
        qid  = str(r.get(f_id))
        opts = r.get(f_opt) if f_opt else None
        if opts and not isinstance(opts, list):
            opts = None   # ignore malformed option fields
        key[qid] = {
            "question": r.get(f_q, ""),
            "options":  opts,
            "answer":   r.get(f_ans),  # str or list
            "is_mcq":   bool(opts),
        }
    print(f"[answer key] loaded {len(key)} questions from {path}")
    return key

# ─────────────────────────────────────────────────────────────────────────────
# CELL 8 — System prompts and user-turn builder
#
# SYSTEM_PROMPT_MATH:
#   Instructs the model to output an EXACT symbolic closed-form answer inside
#   a single \boxed{} — never a decimal approximation. Defines Category 1
#   (discrete integers) vs Category 2 (continuous / pure math) formatting rules.
#
# SYSTEM_PROMPT_MCQ:
#   Ultra-short prompt for MCQ: emit exactly \boxed{X} and nothing else.
#
# build_prompt():
#   Returns (system_prompt, user_message) for a question.
#   For MCQ questions the options are appended to the user turn with letter
#   labels (A, B, C, …) matching the competition format.
# ─────────────────────────────────────────────────────────────────────────────

SYSTEM_PROMPT_MATH = r"""You are an expert mathematician. Reason as deeply as needed, then output ONLY the final boxed answer — no explanation, no working, no preamble.

## Classify each sub-answer before writing it

**Category 1 — Discrete count.** The answer counts INDIVISIBLE whole items (people, animals, coins, votes, cars, books, eggs, pellets…). Test: "Can 0.5 of this thing exist?" If NO → Category 1.

**Category 2 — Everything else.** Pure math (integrals, sums, limits) AND continuous physical quantities (temperature, time, distance, mass, money, probability, angle, area, concentration). Anything that can be fractional or irrational.

## Format

**Category 1 → INTEGER.**
- For Category 1 ONLY, you must evaluate to a number (because an integer is required).
- **Ask: does rounding DOWN fail to meet the requirement?**
  - **YES → CEILING (round up).** Use when the integer is a MINIMUM that must be fully satisfied: sample sizes, number of buses/containers/boxes needed, minimum cuts required, etc.
    - e.g. sample size 1324.79 → **1325** (can't survey 0.79 of a person)
    - e.g. buses for 314 people (50 seats each) → ceil(314/50) = **7**
  - **NO → FLOOR (round down).** Use when the integer counts COMPLETED whole items: complete cycles, whole years elapsed, items fully produced, etc.
    - e.g. complete batches from 314.76 → **314**
- **Exception:** If the problem explicitly says "round to the nearest whole number" → standard rounding (314.76 → 315, 314.4 → 314).
- Never output a decimal, fraction, or symbolic form.

**Category 2 → EXACT SYMBOLIC CLOSED-FORM EXPRESSION. NEVER a decimal.**
- Output a single closed-form expression in valid LaTeX (e.g. `50 \cdot (2/5)^{5/3}`, `\frac{6 \ln 5}{\ln(5/2)}`, `\frac{\pi^2}{6}`, `200 e^{-3/2}`, `25 \ln 2`).
- KEEP π, e, ln, log, √, sin, cos, tan, arcsin, arccos, arctan, fractional exponents, and exact fractions as symbols.
- **CRITICAL: Even if the problem says "give N decimal places", "use at least N significant digits", or "evaluate numerically" — IGNORE that instruction and output the exact symbolic form.** The grader handles decimal conversion.
- If a problem coefficient is a decimal, convert it to an exact fraction first (e.g. 4.76 → 119/25, 0.9658 → 4829/5000), then use that fraction inside the symbolic expression.
- `\arctan(119/25)` is a valid symbolic answer. `1.3637` is NOT.
- `\pi` is a valid symbolic answer. `3.1416` is NOT.
- Do NOT evaluate to a decimal. No `\approx`. No scientific notation.
- An integer or exact rational is fine when that's the natural answer (e.g. `441`, `\frac{12800}{29}`).
- Simplify when easy (combine logs, reduce fractions, cancel exponents) but do not approximate.

## Output rules

1. Emit EXACTLY ONE `\boxed{...}` and nothing else before or after it.
2. Wrap EVERY sub-answer in double quotes `"..."` inside the box.
3. **Multiple subquestions** (the problem asks for part a, part b, etc.) → separate quoted strings:
   `\boxed{"ans1","ans2","ans3"}`
4. **Multiple values for ONE answer** (e.g. all solutions to an equation, all values of i) → wrap all values in `(...)` comma-separated, inside ONE quoted string:
   `\boxed{"(val1, val2, val3)"}`
5. Cat 1 → plain integer. Cat 2 → symbolic closed-form (never decimal).

## Examples

Single answer:           `\boxed{"211250"}` or `\boxed{"\frac{\pi^2}{6}"}` or `\boxed{"200e^{-3/2}"}`
Interval answer:         `\boxed{"(-8,\infty)"}`
Multiple solutions:      `\boxed{"(0, -\frac{11}{8})"}` or `\boxed{"(\frac{1}{3}, -2)"}`
Multiple values of i:    `\boxed{"(2^{-1/8}-1, -2^{-1/8}+1)"}`
Multi-subquestion:       `\boxed{"\arctan(123/31)","e^2"}` or `\boxed{"(50(2/5)^{5/3},50(2/13)^{4/3})","\frac{6\ln5}{\ln(5/2)}"}`
Multi-select MCQ:        `\boxed{"B, C, E, G"}`
Single letter MCQ:       `\boxed{"C"}`
"""

SYSTEM_PROMPT_MCQ = (
    "You are an expert mathematician. Reason as deeply as needed"
    "CRITICAL: Your ENTIRE response must be exactly one token: \\boxed{X} where X is the correct letter."
    " No explanation. No working. No preamble. Just \\boxed{X}."
    " Example of a complete valid response: \\boxed{C}"
    " If your computed answer matches no option, pick the closest. Still output only \\boxed{X}."
)



def build_prompt(question: str, options: Optional[list]):
    """Return (system_prompt, user_message) matching the inference-time format.

    For MCQ questions the option list is rendered with letter labels
    A, B, C, … and appended to the question text.
    """
    if options:
        labels    = [chr(65 + i) for i in range(len(options))]
        opts_text = "\n".join(f"{lbl}. {str(opt).strip()}"
                              for lbl, opt in zip(labels, options))
        return SYSTEM_PROMPT_MCQ, f"{question}\n\nOptions:\n{opts_text}"
    return SYSTEM_PROMPT_MATH, question

# ─────────────────────────────────────────────────────────────────────────────
# CELL 9 — Qwen3-Thinking assistant-turn formatter
#
# build_assistant():
#   Wraps the teacher model's raw solution text as a Qwen3-4B-Thinking
#   assistant turn:
#
#       <think>
#       {reasoning text, with its trailing \boxed{} unwrapped}
#       </think>
#
#       \boxed{final_answer}
#
#   Key decisions:
#   - The ORIGINAL symbolic boxed answer is used (not the numerified version).
#     Numerification was only needed for the judger; the SFT target must be
#     the exact symbolic form the model should learn to produce.
#   - The trailing \boxed{} is unwrapped from the <think> body so that the
#     only real \boxed{} in the turn is the explicit answer after </think>.
#   - DeepSeek output has no <think> tags; we add them because Qwen3-4B-
#     Thinking is trained to separate chain-of-thought from the final answer.
# ─────────────────────────────────────────────────────────────────────────────

def build_assistant(gemini_response: str, final_boxed: str) -> str:
    """Format a correct teacher trace as a Qwen3-Thinking assistant turn.

    Args:
        gemini_response: The full raw teacher output (reasoning + answer).
        final_boxed:     The ORIGINAL symbolic content of the last \\boxed{}
                         (not numerified), used as the SFT answer target.

    Returns:
        A string of the form:
            <think>\n{reasoning}\n</think>\n\n\\boxed{final_boxed}
    """
    body = gemini_response.strip()

    # Remove the trailing \boxed{} from the reasoning body so it isn't
    # duplicated — the explicit \boxed{} after </think> is the canonical one.
    span = find_last_boxed_span(body)
    if span is not None:
        start, end, content = span
        body = (body[:start] + content + body[end:]).strip()

    return f"<think>\n{body}\n</think>\n\n\\boxed{{{final_boxed}}}"

# ─────────────────────────────────────────────────────────────────────────────
# CELL 10.5 — Dry-run preview: randomly sample one question and show outputs
#
# Picks one response at random, runs it through the full pipeline, and prints
# exactly what would be written to OUT_SFT, OUT_KEPT, and OUT_REPORT.
# Nothing is written to disk — safe to run at any time for a sanity check.
# ─────────────────────────────────────────────────────────────────────────────

import random

def preview_one():
    judger = get_judger()
    key    = load_answer_key(ANSWER_KEY_PATH)
    gem    = [json.loads(l) for l in open(DEEPSEEK_PATH, encoding="utf-8") if l.strip()]

    # Shuffle and find the first response that passes every filter
    random.shuffle(gem)
    for rec in gem:
        qid  = str(rec.get("question_id", rec.get("id")))
        resp = rec.get("response") or ""
        thinking = rec.get("thinking") or ""
        stop = rec.get("stop_reason", "")

        if REQUIRE_FINISHED and stop.upper() != "STOP":
            continue
        info = key.get(qid)
        if info is None:
            continue
        pred_box = (rec.get("boxed") or "").strip() or extract_boxed(resp)
        if not pred_box:
            continue
        numerified = numerify_response(resp)
        ok = score_mcq(numerified, info["answer"]) if info["is_mcq"] else judge_free(judger, numerified, info["answer"])
        if not ok:
            continue

        # ── Found a correct, complete response — build all three outputs ──
        system, user = build_prompt(info["question"], info["options"])
        assistant = build_assistant(thinking, pred_box)
        kept_record  = {
            "question_id": qid,
            "is_mcq":      info["is_mcq"],
            "gold":        info["answer"],
            "pred_boxed":  pred_box,
            "messages": [
                {"role": "system",    "content": system},
                {"role": "user",      "content": user},
                {"role": "assistant", "content": assistant},
            ],
        }

        SEP = "\n" + "═"*70 + "\n"

        print(SEP)
        print(f"  question_id : {qid}   |   is_mcq : {info['is_mcq']}")
        print(f"  gold answer : {info['answer']}")
        print(f"  pred_boxed  : {pred_box}")

        print(SEP + "OUT_SFT  (one line of sft_data.jsonl)\n")
        print(json.dumps({"messages": kept_record["messages"]}, ensure_ascii=False, indent=2))

        print(SEP + "OUT_KEPT  (one line of kept_correct.jsonl)\n")
        print(json.dumps({k: v for k, v in kept_record.items() if k != "messages"}, ensure_ascii=False, indent=2))

        print(SEP + "OUT_REPORT  (grading_report.txt excerpt)\n")
        print("=== DeepSeek-V4-Pro grading report (official judger.Judger) ===")
        print("  [preview — counts shown for this single example]")
        print(f"  gradeable responses       : 1")
        print(f"  KEPT for SFT              : 1  (free={int(not info['is_mcq'])}, mcq={int(info['is_mcq'])})")
        print(f"  teacher accuracy          : 100.0%")
        print(SEP)
        return

    print("[preview] No correct finished response found in a random scan — try again or check filters.")

preview_one()

# ─────────────────────────────────────────────────────────────────────────────
# CELL 10 — Main rejection-sampling pipeline
#
# This cell ties everything together:
#   1. Creates OUT_DIR (deepseekv4-pro/) if it does not exist.
#   2. Loads the judger, answer key, and teacher model responses.
#   3. For each response:
#        a. Skip if unfinished (stop_reason != STOP) and REQUIRE_FINISHED=True.
#        b. Skip if the question_id has no entry in the answer key.
#        c. Skip if no \boxed{} answer found in the response.
#        d. Numerify the response, then judge with the official judger.
#        e. Skip duplicates (same qid + same response text).
#        f. If ONE_PER_QUESTION=True, skip extra correct attempts.
#        g. Build the SFT message dict and accumulate.
#   4. Writes all outputs into deepseekv4-pro/:
#        sft_data.jsonl      → messages only (plug into training loop)
#        kept_correct.jsonl  → full records for inspection
#        grading_report.txt  → counts + teacher accuracy
# ─────────────────────────────────────────────────────────────────────────────

def main():
    if not os.path.exists(DEEPSEEK_PATH):
        sys.exit(f"[error] DEEPSEEK_PATH not found: {DEEPSEEK_PATH}")

    # --- Step 0: ensure output directory exists ---
    os.makedirs(OUT_DIR, exist_ok=True)
    print(f"[output dir] {os.path.abspath(OUT_DIR)}")

    # --- Step 1: initialise judger and load data ---
    judger = get_judger()                    # competition's official grader
    key    = load_answer_key(ANSWER_KEY_PATH)

    gem = [json.loads(l) for l in open(DEEPSEEK_PATH, encoding="utf-8") if l.strip()]
    print(f"[responses]  loaded {len(gem)} responses from {DEEPSEEK_PATH}")

    stats = Counter()
    kept, wrong_kept, seen, kept_qids = [], [], set(), set()

    # --- Step 2: iterate and rejection-sample ---
    for rec in gem:
        stats["total"] += 1
        qid  = str(rec.get("question_id", rec.get("id")))
        resp = rec.get("response") or ""
        thinking = rec.get("thinking") or ""
        stop = rec.get("stop_reason", "")

        # (a) Drop unfinished responses — truncated traces have no usable \boxed{}
        if REQUIRE_FINISHED and stop.upper() != "STOP":
            stats["dropped_unfinished"] += 1
            continue

        # (b) Drop if question_id not in answer key
        info = key.get(qid)
        if info is None:
            stats["dropped_no_goldkey"] += 1
            continue

        # (c) Extract the ORIGINAL symbolic boxed answer (used for SFT target)
        pred_box = (rec.get("boxed") or "").strip() or extract_boxed(resp)
        print("this is the responds: " + resp)
        print("this is the pred_box: " + pred_box)

        if not pred_box:
            stats["dropped_no_box"] += 1
            continue

        # (d) Grade: numerify first, then run the official judger


        is_mcq = info["is_mcq"]
        if is_mcq:
            ok = score_mcq(resp, info["answer"])
        else:
            numerified = numerify_response(resp)
            print("this is the numerified: " + numerified)
            ok = judge_free(judger, numerified, info["answer"])
        if not ok:
          stats["dropped_incorrect"] += 1
          wrong_kept.append({
              "question_id": qid,
              "is_mcq":      is_mcq,
              "gold":        info["answer"],
              "pred_boxed":  pred_box,
              "stop_reason": stop,
              "response":    resp,
              "thinking":    thinking,
          })
          continue

        # (e) Deduplication: same question + same response text → skip
        attempt = rec.get("attempt", rec.get("attempt_id"))
        dedup_k = (qid, attempt)
        if dedup_k in seen:
            stats["dropped_duplicate"] += 1
            continue
        seen.add(dedup_k)

        # (f) If ONE_PER_QUESTION, keep only the first correct trace per qid
        if ONE_PER_QUESTION and qid in kept_qids:
            stats["dropped_extra_per_q"] += 1
            continue
        kept_qids.add(qid)

        # (g) Build the SFT example in Qwen3-Thinking chat format
        system, user = build_prompt(info["question"], info["options"])
        assistant = build_assistant(thinking, pred_box)
        kept.append({
            "question_id": qid,
            "is_mcq":      is_mcq,
            "gold":        info["answer"],
            "pred_boxed":  pred_box,
            "messages": [
                {"role": "system",    "content": system},
                {"role": "user",      "content": user},
                {"role": "assistant", "content": assistant},
            ],
        })
        stats["kept"] += 1
        stats["kept_mcq" if is_mcq else "kept_free"] += 1

    # --- Step 3: write all outputs into deepseekv4-pro/ ---

    # sft_data.jsonl — only the messages list (plug straight into a training loop)
    with open(OUT_SFT, "w", encoding="utf-8") as f:
        for k in kept:
            f.write(json.dumps({"messages": k["messages"]}, ensure_ascii=False) + "\n")

    # kept_correct.jsonl — full metadata for inspection / debugging
    with open(OUT_KEPT, "w", encoding="utf-8") as f:
        for k in kept:
            f.write(json.dumps(k, ensure_ascii=False) + "\n")
    # kept_wrong.jsonl — incorrect responses, same shape as kept_correct.jsonl
    with open(OUT_WRONG, "w", encoding="utf-8") as f:
        for w in wrong_kept:
            f.write(json.dumps(w, ensure_ascii=False) + "\n")

    # grading_report.txt — human-readable stats
    graded = (
        stats["total"]
        - stats["dropped_unfinished"]
        - stats["dropped_no_goldkey"]
        - stats["dropped_no_box"]
    )
    acc = (stats["kept"] / graded * 100) if graded else 0.0
    report = [
        "=== DeepSeek-V4-Pro grading report (official judger.Judger) ===",
        f"total responses           : {stats['total']}",
        f"  dropped (unfinished)    : {stats['dropped_unfinished']}",
        f"  dropped (no answer key) : {stats['dropped_no_goldkey']}",
        f"  dropped (no boxed)      : {stats['dropped_no_box']}",
        f"  dropped (incorrect)     : {stats['dropped_incorrect']}",
        f"  dropped (duplicate)     : {stats['dropped_duplicate']}",
        f"  dropped (extra per q)   : {stats['dropped_extra_per_q']}",
        f"gradeable responses       : {graded}",
        f"KEPT for SFT              : {stats['kept']}   "
        f"(free={stats['kept_free']}, mcq={stats['kept_mcq']})",
        f"teacher accuracy (kept/gradeable) : {acc:.1f}%",
        "",
        f"wrote: {OUT_SFT}  ({stats['kept']} training examples)",
        f"wrote: {OUT_KEPT}  (full info for inspection)",
        f"wrote: {OUT_WRONG}  ({len(wrong_kept)} incorrect responses)",
        f"wrote: {OUT_REPORT}",
    ]
    text = "\n".join(report)
    print("\n" + text)
    with open(OUT_REPORT, "w", encoding="utf-8") as f:
        f.write(text + "\n")

    if stats["kept"] == 0:
        print("\n[warning] 0 examples kept — check that the answer key joins on "
              "question_id and that judger.py imported correctly.")

main()

import shutil
shutil.move("/content/deepseekv4-pro",
            "/content/151B_SP26_Competition")

# Zip the whole folder (excludes any HF cache that might've ended up inside)
!cd /content && zip -rq 151B_SP26_Competition_dsv4_data.zip 151B_SP26_Competition \
    -x "151B_SP26_Competition/__pycache__/*" \
       "151B_SP26_Competition/.ipynb_checkpoints/*"

# Copy zip to Drive

# Verify
!cp /content/151B_SP26_Competition_dsv4_data.zip /content/drive/MyDrive/CSE\ 151B/
!ls -lh /content/drive/MyDrive/CSE\ 151B/151B_SP26_Competition_dsv4_data.zip

