# -*- coding: utf-8 -*-
"""GRPO

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13NIrMlylTfQb6ifkEcVmBZ61atPJEk5I
"""

# !pip install -q \
#     transformers \
#     "trl==0.12.0" \
#     "peft>=0.11.0,<0.14.0" \
#     "datasets>=2.20.0" \
#     "accelerate>=0.30.0" \
#     "scipy"
# !pip install -q --force-reinstall "sympy==1.12"
# !pip install -q --force-reinstall "antlr4-python3-runtime==4.11.1"
# !pip install --upgrade --force-reinstall "transformers>=4.51.0"
# !pip install -q --force-reinstall "peft>=0.11.0,<0.14.0"
# !pip install --force-reinstall "trl==0.14.0"
#!pip uninstall -y torchvision
# DO NOT install vllm — it's pre-installed at 0.21.0, matched to this torch build
# !pip install -q \
#     "transformers>=4.51.0" \
#     "trl==0.14.0" \
#     "peft>=0.11.0,<0.14.0" \
#     "datasets>=2.20.0" \
#     "accelerate>=0.30.0" \
#     "scipy"
# !pip install -q --force-reinstall "sympy==1.12"
# !pip install -q --force-reinstall "antlr4-python3-runtime==4.11.1"
# !pip uninstall -y torchvision 2>/dev/null; true
# # !pip uninstall -y vllm
!pip install -q \
    "transformers>=4.51.0" \
    "trl" \
    "peft>=0.11.0,<0.14.0" \
    "datasets>=2.20.0" \
    "accelerate>=0.30.0" \
    "scipy"
!pip install -q --force-reinstall "sympy==1.12"
!pip install -q --force-reinstall "antlr4-python3-runtime==4.11.1"
!pip install -q --force-reinstall trl   # force clean reinstall to avoid mixed-version bugs
!pip uninstall -y torchvision 2>/dev/null; true
# !pip install --force-reinstall --upgrade trl
!pip install -q "numpy<2.0" transformers accelerate
!pip instal vllm

from google.colab import drive
drive.mount('/content/drive')

# Commented out IPython magic to ensure Python compatibility.
!unzip -q "/content/drive/MyDrive/CSE 151B/151B_SP26_Competition_dsv4_ft.zip" -d /content/
!ls /content/151B_SP26_Competition
# %cd /content/151B_SP26_Competition

import os, sys

DRIVE_ROOT  = "/content/drive/MyDrive/CSE 151B"
DATA_FILE   = f"{DRIVE_ROOT}/rl_data/rl_data_3000.jsonl"
# SFT checkpoint produced by your SFT run (set to None to start from HF base)
SFT_CKPT    = "/content/151B_SP26_Competition/deepseekv4-pro/qwen3-4b-sft-lora/checkpoint-396"
GRPO_CKPT   = f"{DRIVE_ROOT}/checkpoints/grpo_checkpoint"
os.makedirs(GRPO_CKPT, exist_ok=True)

# Judger lives here (copy judger.py + helper modules from competition repo)
JUDGER_PATH = "/content/151B_SP26_Competition/"   # adjust if judger.py is in a sub-folder
sys.path.insert(0, JUDGER_PATH)

print("Drive mounted ✓")
print(f"Data    : {DATA_FILE}")
print(f"SFT ckpt: {SFT_CKPT}")
print(f"Out dir : {GRPO_CKPT}")

# ═══════════════════════════════════════════════════════════════════════════════
# Cell 3 – Judger + numerification helpers
#           Copied verbatim from private_inference.py so the reward function
#           uses the EXACT same pipeline as competition scoring.
# ═══════════════════════════════════════════════════════════════════════════════
import re, io, contextlib, json, math as _math
import sympy as sp
from sympy.parsing.latex import parse_latex

# -- Import competition judger ------------------------------------------------
from judger import Judger
judger = Judger(strict_extract=False)

N_DIGITS  = 10
WORK_PREC = N_DIGITS + 6

# ── Box-finding ───────────────────────────────────────────────────────────────

def find_last_boxed_span(text: str):
    """Return (start, end, content) of the last complete \\boxed{...}, or None."""
    if not text: return None
    needle, n, last, i = r"\boxed", len(text), None, 0
    while True:
        idx = text.find(needle, i)
        if idx == -1: break
        j = idx + len(needle)
        while j < n and text[j].isspace(): j += 1
        if j >= n or text[j] != "{":
            i = idx + len(needle); continue
        depth, k, sc = 1, j + 1, j + 1
        while k < n and depth > 0:
            ch = text[k]
            if ch == "\\" and k + 1 < n: k += 2; continue
            if ch == "{":   depth += 1
            elif ch == "}":
                depth -= 1
                if depth == 0: break
            k += 1
        if depth == 0:
            last = (idx, k + 1, text[sc:k]); i = k + 1
        else:
            i = idx + len(needle)
    return last


_BOXED_RE = re.compile(r"\\?b?oxed\s*\{", re.IGNORECASE)

def find_last_balanced_boxed(text: str):
    """Find the last \\boxed{} even when the leading \\ or 'b' is missing
    (e.g. 'oxed{E}' produced by some models).  More robust than
    find_last_boxed_span for raw model output."""
    last = None
    for m in _BOXED_RE.finditer(text):
        if "oxed{" not in m.group().replace(" ", ""): continue
        brace_open = m.end() - 1
        depth, i, n = 1, brace_open + 1, len(text)
        while i < n and depth > 0:
            ch = text[i]
            if ch == "\\" and i + 1 < n: i += 2; continue
            if ch == "{":   depth += 1
            elif ch == "}":
                depth -= 1
                if depth == 0: break
            i += 1
        if depth == 0:
            last = (m.start(), i + 1, text[brace_open + 1 : i])
    return last


def fix_box_text(text: str) -> str:
    """Normalize the last boxed expression to \\boxed{...}.

    MUST run BEFORE numerify_response — a broken 'oxed{E}' is invisible to
    find_last_boxed_span, so numerification would silently do nothing.
    """
    span = find_last_balanced_boxed(text)
    if span is None: return text
    start, end, inner = span
    correct = "\\boxed{" + inner + "}"
    if text[start:end] == correct: return text
    return text[:start] + correct + text[end:]


# ── String splitters ──────────────────────────────────────────────────────────

def split_top_level_commas(s: str):
    """Split on commas not inside any brace or paren (handles \\left...\\right)."""
    out, depth, start, i, n = [], 0, 0, 0, len(s)
    while i < n:
        ch = s[i]
        if ch == "\\" and i + 1 < n: i += 2; continue
        if ch in "{(":   depth += 1
        elif ch in "})": depth -= 1
        elif ch == "," and depth == 0:
            out.append(s[start:i]); start = i + 1
        i += 1
    out.append(s[start:])
    return [p.strip() for p in out if p.strip()]


def split_quoted_answers(content: str):
    """Split \\boxed{"ans1","ans2"} content on commas OUTSIDE double-quotes.
    Returns list of unquoted strings, or None if no quotes present."""
    content = content.strip()
    if '"' not in content: return None
    parts, current, in_q = [], [], False
    for ch in content:
        if ch == '"':
            in_q = not in_q
        elif ch == ',' and not in_q:
            p = ''.join(current).strip()
            if p: parts.append(p)
            current = []
        else:
            current.append(ch)
    p = ''.join(current).strip()
    if p: parts.append(p)
    return parts or None


def compress_letter_list(s: str) -> str:
    """'A, B, C' → 'ABC' for multi-select MCQ answers."""
    parts = [p.strip() for p in s.split(',')]
    if len(parts) > 1 and all(re.fullmatch(r'[A-Za-z]', p) for p in parts):
        return ''.join(p.upper() for p in parts)
    return s


# ── LaTeX cleaning + evaluation ───────────────────────────────────────────────

_CLEANUPS = [
    (r"\\dfrac",           r"\\frac"),
    (r"\\tfrac",           r"\\frac"),
    (r"\\!",               ""),
    (r"\\,",               ""),
    (r"\\;",               ""),
    (r"\\ ",               ""),
    (r"\\\\ ",             " "),
    (r"\\left",            ""),
    (r"\\right",           ""),
    (r"\\$",               ""),
    (r"\\%",               ""),
    (r"\\text\{([^}]*)\}", r"\1"),   # \text{C} → C
]

def _clean_latex(s: str) -> str:
    s = s.strip()
    def _deg2rad(m):
        return "{" + str(_math.radians(float(m.group(1)))) + "}"
    s = re.sub(r"(\d+(?:\.\d+)?)\s*\^(\{)?\\circ(?(2)\})", _deg2rad, s)
    s = re.sub(r"(\d+(?:\.\d+)?)\s*°", _deg2rad, s)
    for pat, rep in _CLEANUPS:
        s = re.sub(pat, rep, s)
    return re.sub(r"^=\s*", "", s).strip()


def _format_numeric(val, n_digits: int) -> str:
    re_part, im_part = val.as_real_imag()
    re_f, im_f = float(re_part), float(im_part)
    if _math.isinf(re_f): return "\\infty" if re_f > 0 else "-\\infty"
    if abs(im_f) < 1e-12: return f"{re_f:.{n_digits}f}"
    sign = "+" if im_f >= 0 else ""
    return f"{re_f:.{n_digits}f}{sign}{im_f:.{n_digits}f}i"


def _sub_stat_quantiles(s: str) -> str:
    try:
        from scipy import stats as _sc
        s = re.sub(r"\bz\s*_\{?\s*([0-9.]+)\s*\}?",
                   lambda m: str(_sc.norm.ppf(1 - float(m.group(1)))), s)
        s = re.sub(r"\\?chi\^?2\s*_\{?\s*([0-9.]+)\s*,\s*([0-9]+)\s*\}?",
                   lambda m: str(_sc.chi2.ppf(1 - float(m.group(1)), int(m.group(2)))),
                   s, flags=re.IGNORECASE)
        s = re.sub(
            r"\bt\s*_\{?\s*([0-9.]+)\s*,\s*\\frac\{([0-9]+)\}\{([0-9]+)\}\s*\}?",
            lambda m: str(_sc.t.ppf(1 - float(m.group(1)),
                                    float(m.group(2)) / float(m.group(3)))), s)
        s = re.sub(r"\bt\s*_\{?\s*([0-9.]+)\s*,\s*([0-9.]+)\s*\}?",
                   lambda m: str(_sc.t.ppf(1 - float(m.group(1)), float(m.group(2)))), s)
        s = re.sub(r"\bF\s*_\{?\s*([0-9.]+)\s*,\s*([0-9]+)\s*,\s*([0-9]+)\s*\}?",
                   lambda m: str(_sc.f.ppf(1 - float(m.group(1)),
                                           int(m.group(2)), int(m.group(3)))), s)
    except ImportError:
        pass
    return s


def _eval_cdf_expression(s: str, n_digits: int, _depth: int = 0):
    if "\\Phi" not in s and "\\Pr" not in s: return None
    try:
        from scipy import stats as _sc
        def _inner(expr):
            if _depth >= 2: return None
            try: return float(evaluate_piece(expr.strip(), n_digits, _depth + 1))
            except: return None
        w = s
        w = re.sub(r"\\Phi\s*\^\{-1\}\s*\(([^)]+)\)",
                   lambda m: (f"{_sc.norm.ppf(v):.{n_digits}f}"
                              if (v := _inner(m.group(1))) is not None else m.group(0)), w)
        w = re.sub(r"\\Phi\s*\(([^)]+)\)",
                   lambda m: (f"{_sc.norm.cdf(v):.{n_digits}f}"
                              if (v := _inner(m.group(1))) is not None else m.group(0)), w)
        w = re.sub(r"\\Pr\s*\(\s*T_\{?(\d+)\}?\s*<\s*([^)]+)\)",
                   lambda m: (f"{_sc.t.cdf(_inner(m.group(2)), _inner(m.group(1))):.{n_digits}f}"
                              if _inner(m.group(1)) is not None else m.group(0)), w)
        if w == s: return None
        try: return f"{float(w):.{n_digits}f}"
        except: pass
        try:
            val = sp.N(sp.sympify(w), WORK_PREC)
            return _format_numeric(val, n_digits)
        except: pass
        return w
    except: return None


def evaluate_piece(piece: str, n_digits: int = N_DIGITS, _depth: int = 0) -> str:
    """Convert one boxed sub-answer to an N-digit decimal string."""
    p = (piece or "").strip()
    if not p: return p
    if re.fullmatch(r"[A-Z]", p):      return p   # MCQ letter — never parse
    if re.fullmatch(r"-?\d+", p):      return p   # plain integer
    if re.fullmatch(r"-?\d+\.\d+", p):
        try: return f"{float(p):.{n_digits}f}"
        except: pass
    s = _clean_latex(p)
    if re.fullmatch(r"[A-Z]+", s): return s        # \text{C} → C after cleaning
    s = _sub_stat_quantiles(s)
    cdf = _eval_cdf_expression(s, n_digits, _depth)
    if cdf is not None: return cdf
    try:
        expr = parse_latex(s)
        if isinstance(expr, sp.Eq): expr = expr.rhs
        expr = expr.subs([(sp.Symbol('pi'), sp.pi),
                          (sp.Symbol('e'),  sp.E),
                          (sp.Symbol('i'),  sp.I)])
        return _format_numeric(sp.N(expr, WORK_PREC), n_digits)
    except: pass
    try:
        expr = sp.sympify(s.replace("\\", ""))
        return _format_numeric(sp.N(expr, WORK_PREC), n_digits)
    except: pass
    try:
        from scipy import stats as _sc
        m = re.search(r"chi\^?2\s*_\{?\s*([0-9.]+)\s*,\s*([0-9]+)\s*\}?", p, re.I)
        if m: return f"{_sc.chi2.ppf(1-float(m.group(1)),int(m.group(2))):.{n_digits}f}"
        m = re.search(r"[Ff]\s*_\{?\s*([0-9.]+)\s*,\s*([0-9]+)\s*,\s*([0-9]+)\s*\}?", p)
        if m: return f"{_sc.f.ppf(1-float(m.group(1)),int(m.group(2)),int(m.group(3))):.{n_digits}f}"
        m = re.search(r"\bt\s*_\{?\s*([0-9.]+)\s*,\s*([0-9]+)\s*\}?", p)
        if m: return f"{_sc.t.ppf(1-float(m.group(1)),float(m.group(2))):.{n_digits}f}"
        m = re.search(r"\bz\s*_\{?\s*([0-9.]+)\s*\}?", p)
        if m: return f"{_sc.norm.ppf(1-float(m.group(1))):.{n_digits}f}"
    except: pass
    return p   # give up — return original


def numerify_paren_list(s: str, n_digits: int = N_DIGITS) -> str:
    """Numerify a sub-answer that may be a parenthesised value list."""
    inner = re.sub(r"\\left\s*", "", s.strip())
    inner = re.sub(r"\\right\s*", "", inner).strip()
    if inner.startswith('(') and inner.endswith(')'):
        parts = split_top_level_commas(inner[1:-1])
        if len(parts) > 1:
            return '(' + ', '.join(evaluate_piece(p, n_digits) for p in parts) + ')'
    return evaluate_piece(s, n_digits)


def numerify_response(text: str, n_digits: int = N_DIGITS) -> str:
    """Numerify the last \\boxed{} in-place.  Handles quoted AND legacy formats.

    Call AFTER fix_box_text — requires a well-formed \\boxed{}.
    Quoted  : \\boxed{"ans1","ans2"} → \\boxed{"num1","num2"}  (quotes preserved)
    Legacy  : \\boxed{a, b}          → \\boxed{num_a, num_b}
    """
    try:
        span = find_last_boxed_span(text)
        if span is None: return text
        start, end, content = span
        quoted = split_quoted_answers(content)
        if quoted is not None:
            new_parts = [numerify_paren_list(compress_letter_list(p), n_digits)
                         for p in quoted]
            new_box = "\\boxed{" + ",".join(f'"{p}"' for p in new_parts) + "}"
            return text[:start] + new_box + text[end:]
        parts = split_top_level_commas(content)
        if not parts: return text
        new_box = "\\boxed{" + ", ".join(numerify_paren_list(p, n_digits)
                                         for p in parts) + "}"
        return text[:start] + new_box + text[end:]
    except:
        return text


# ── MCQ letter extractor ─────────────────────────────────────────────────────

def extract_letter(text: str) -> str:
    """Return the single letter inside \\boxed{X}, or the last A-Z in the text."""
    m = re.search(r"\\boxed\{([A-Za-z])\}", text or "")
    if m: return m.group(1).upper()
    matches = re.findall(r"\b([A-Z])\b", (text or "").upper())
    return matches[-1] if matches else ""


# ── Unified cleaning pipeline ─────────────────────────────────────────────────

def clean_response(text: str) -> str:
    """Full cleaning pipeline for a model completion (or a gold string wrapped
    in \\boxed{}).

    Steps (matching private_inference.py):
      1. fix_box_text  — normalise broken 'oxed{…}' variants
      2. numerify_response — evaluate LaTeX/sympy numerically
      3. strip quotes  — \\boxed{"3","5"} → \\boxed{3,5}  (judger expects bare)
    """
    fixed      = fix_box_text(text)
    numerified = numerify_response(fixed)
    span = find_last_boxed_span(numerified)
    if span is not None:
        start, end, content = span
        quoted = split_quoted_answers(content)
        if quoted is not None:
            new_box = "\\boxed{" + ",".join(quoted) + "}"
            numerified = numerified[:start] + new_box + numerified[end:]
    return numerified


def clean_gold_value(s: str) -> str:
    """Numerify a raw gold string so it matches the scale of a numerified pred.

    Wraps the string in \\boxed{"s"}, runs the full pipeline, and returns
    the extracted (unquoted, numerified) content.
    """
    fake_text = f'\\boxed{{"{s}"}}'
    cleaned   = clean_response(fake_text)
    span      = find_last_boxed_span(cleaned)
    if span is None: return s
    content = span[2]
    # content is now unquoted (clean_response stripped quotes)
    return content.strip()


print("Helpers loaded ✓")



# ═══════════════════════════════════════════════════════════════════════════════
# Cell 4b – Patch adapter_config.json (removes fields added in peft>=0.14.0)
# Run once before Cell 5. Safe to re-run — already-removed keys are ignored.
# ═══════════════════════════════════════════════════════════════════════════════
import json as _json

_cfg_path = os.path.join(SFT_CKPT, "adapter_config.json")
if os.path.isfile(_cfg_path):
    with open(_cfg_path) as _f:
        _cfg = _json.load(_f)
    _unknown = [
        "alora_invocation_tokens", "alora_init_method", "alora_rank_pattern",
        "arrow_config", "corda_config", "ensure_weight_tying", "eva_config",
        "exclude_modules", "layer_replication", "lora_bias", "lora_ga_config",
        "peft_version", "qalora_group_size", "target_parameters",
        "trainable_token_indices", "use_bdlora", "use_qalora",
    ]
    removed = [k for k in _unknown if _cfg.pop(k, None) is not None]
    with open(_cfg_path, "w") as _f:
        _json.dump(_cfg, _f, indent=2)
    print(f"adapter_config.json patched — removed: {removed}")
else:
    print("No adapter_config.json found (will load base model)")

# ═══════════════════════════════════════════════════════════════════════════════
# Cell 5 – Load tokenizer + model
# ═══════════════════════════════════════════════════════════════════════════════
import torch
from transformers import AutoTokenizer, AutoModelForCausalLM
from peft import LoraConfig, get_peft_model, PeftModel

MODEL_ID = "Qwen/Qwen3-4B-Thinking-2507"   # ← must match adapter_config.json

# --- Tokenizer ----------------------------------------------------------------
tokenizer = AutoTokenizer.from_pretrained(
    MODEL_ID,
    trust_remote_code=True,
    padding_side="left",    # GRPOTrainer needs left-padding for batched generation
)
if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token

# --- Model — load base, merge SFT LoRA, then attach fresh GRPO LoRA -----------
if os.path.isdir(SFT_CKPT):
    print(f"Loading SFT LoRA checkpoint from {SFT_CKPT} ...")
    base = AutoModelForCausalLM.from_pretrained(
        MODEL_ID,
        torch_dtype=torch.bfloat16,
        device_map="auto",
        trust_remote_code=True,
        attn_implementation="sdpa",
    )
    model = PeftModel.from_pretrained(base, SFT_CKPT)
    model = model.merge_and_unload()
    print("SFT LoRA merged ✓")
else:
    print(f"SFT checkpoint not found — loading base model {MODEL_ID}")
    model = AutoModelForCausalLM.from_pretrained(
        MODEL_ID,
        torch_dtype=torch.bfloat16,
        device_map="auto",
        trust_remote_code=True,
        attn_implementation="sdpa",
    )

# --- Attach fresh LoRA for GRPO -----------------------------------------------
lora_config = LoraConfig(
    r=32,
    lora_alpha=64,
    target_modules=[
        "q_proj", "k_proj", "v_proj", "o_proj",
        "gate_proj", "up_proj", "down_proj",
    ],
    lora_dropout=0.05,
    bias="none",
    task_type="CAUSAL_LM",
)
model = get_peft_model(model, lora_config)
model.print_trainable_parameters()

print("Model ready ✓")

# ═══════════════════════════════════════════════════════════════════════════════
# Cell 4 – Load rl_data_3000.jsonl → HuggingFace Dataset
# ═══════════════════════════════════════════════════════════════════════════════
from datasets import Dataset

records = []
with open(DATA_FILE, encoding="utf-8") as f:
    for line in f:
        rec = json.loads(line)
        records.append(rec)

print(f"Loaded {len(records)} records")

# Summarise btypes
from collections import Counter
btype_dist = Counter(r["btype"] for r in records)
for bt, n in btype_dist.most_common():
    print(f"  {bt:10s} {n:5d}  ({n/len(records)*100:.1f}%)")

# ── System prompts ────────────────────────────────────────────────────────────
SYSTEM_PROMPT_MATH = r"""You are an expert mathematician. Reason as deeply as needed, then output ONLY the final boxed answer — no explanation, no working, no preamble.

## Classify each sub-answer before writing it

**Category 1 — Discrete count.** The answer counts INDIVISIBLE whole items (people, animals, coins, votes, cars, books, eggs, pellets…). Test: "Can 0.5 of this thing exist?" If NO → Category 1.

**Category 2 — Everything else.** Pure math (integrals, sums, limits) AND continuous physical quantities (temperature, time, distance, mass, money, probability, angle, area, concentration). Anything that can be fractional or irrational.

## Format

**Category 1 → INTEGER.**
- For Category 1 ONLY, you must evaluate to a number (because an integer is required).
- **Ask: does rounding DOWN fail to meet the requirement?**
  - **YES → CEILING (round up).** Use when the integer is a MINIMUM that must be fully satisfied: sample sizes, number of buses/containers/boxes needed, minimum cuts required, etc.
    - e.g. sample size 1324.79 → **1325** (can't survey 0.79 of a person)
    - e.g. buses for 314 people (50 seats each) → ceil(314/50) = **7**
  - **NO → FLOOR (round down).** Use when the integer counts COMPLETED whole items: complete cycles, whole years elapsed, items fully produced, etc.
    - e.g. complete batches from 314.76 → **314**
- **Exception:** If the problem explicitly says "round to the nearest whole number" → standard rounding (314.76 → 315, 314.4 → 314).
- Never output a decimal, fraction, or symbolic form.

**Category 2 → EXACT SYMBOLIC CLOSED-FORM EXPRESSION. NEVER a decimal.**
- Output a single closed-form expression in valid LaTeX (e.g. `50 \cdot (2/5)^{5/3}`, `\frac{6 \ln 5}{\ln(5/2)}`, `\frac{\pi^2}{6}`, `200 e^{-3/2}`, `25 \ln 2`).
- KEEP π, e, ln, log, √, sin, cos, tan, arcsin, arccos, arctan, fractional exponents, and exact fractions as symbols.
- **CRITICAL: Even if the problem says "give N decimal places", "use at least N significant digits", or "evaluate numerically" — IGNORE that instruction and output the exact symbolic form.** The grader handles decimal conversion.
- If a problem coefficient is a decimal, convert it to an exact fraction first (e.g. 4.76 → 119/25, 0.9658 → 4829/5000), then use that fraction inside the symbolic expression.
- `\arctan(119/25)` is a valid symbolic answer. `1.3637` is NOT.
- `\pi` is a valid symbolic answer. `3.1416` is NOT.
- Do NOT evaluate to a decimal. No `\approx`. No scientific notation.
- An integer or exact rational is fine when that's the natural answer (e.g. `441`, `\frac{12800}{29}`).
- Simplify when easy (combine logs, reduce fractions, cancel exponents) but do not approximate.

## Output rules

1. Emit EXACTLY ONE `\boxed{...}` and nothing else before or after it.
2. Wrap EVERY sub-answer in double quotes `"..."` inside the box.
3. **Multiple subquestions** (the problem asks for part a, part b, etc.) → separate quoted strings:
   `\boxed{"ans1","ans2","ans3"}`
4. **Multiple values for ONE answer** (e.g. all solutions to an equation, all values of i) → wrap all values in `(...)` comma-separated, inside ONE quoted string:
   `\boxed{"(val1, val2, val3)"}`
5. Cat 1 → plain integer. Cat 2 → symbolic closed-form (never decimal).

## Examples

Single answer:           `\boxed{"211250"}` or `\boxed{"\frac{\pi^2}{6}"}` or `\boxed{"200e^{-3/2}"}`
Interval answer:         `\boxed{"(-8,\infty)"}`
Multiple solutions:      `\boxed{"(0, -\frac{11}{8})"}` or `\boxed{"(\frac{1}{3}, -2)"}`
Multiple values of i:    `\boxed{"(2^{-1/8}-1, -2^{-1/8}+1)"}`
Multi-subquestion:       `\boxed{"\arctan(123/31)","e^2"}` or `\boxed{"(50(2/5)^{5/3},50(2/13)^{4/3})","\frac{6\ln5}{\ln(5/2)}"}`
Multi-select MCQ:        `\boxed{"B, C, E, G"}`
Single letter MCQ:       `\boxed{"C"}`
"""

SYSTEM_PROMPT_MCQ = (
    "You are an expert mathematician. Reason as deeply as needed. "
    "CRITICAL: Your ENTIRE response must be exactly one token: \\boxed{X} where X is the correct letter."
    " No explanation. No working. No preamble. Just \\boxed{X}."
    " Example of a complete valid response: \\boxed{C}"
    " If your computed answer matches no option, pick the closest. Still output only \\boxed{X}."
)

# ── Build the 'prompt' field required by GRPOTrainer ──────────────────────────
# GRPOTrainer expects a 'prompt' column: a list of chat messages
# (same format as AutoTokenizer.apply_chat_template input).

def record_to_messages(rec: dict) -> list[dict]:
    system = SYSTEM_PROMPT_MCQ if rec.get("btype") == "mcq" else SYSTEM_PROMPT_MATH
    return [
        {"role": "system", "content": system},
        {"role": "user",   "content": rec["problem"]},
    ]

hf_data = Dataset.from_list([
    {
        "prompt": tokenizer.apply_chat_template(
            record_to_messages(r),
            tokenize=False,
            add_generation_prompt=True,
            enable_thinking=True,   # ← add this
        ),
        "gt_display": r["gt_display"],
        "btype":      r["btype"],
    }
    for r in records
])

print(f"Dataset columns: {hf_data.column_names}")
print(f"Example prompt:\n{hf_data[0]['prompt']}")

# ═══════════════════════════════════════════════════════════════════════════════
# Cell 6 – Reward function
# ═══════════════════════════════════════════════════════════════════════════════
# Pipeline — both pred AND gold go through the same clean_response():
#
#   PRED:  completion  → clean_response() → numerified \boxed{...}
#   GOLD:  gt_display  → clean_response() → numerified \boxed{...}
#                      → extract content (split_top_level_commas for subpart)
#
# gt_display is already \boxed{"answer"} or \boxed{"p1","p2"} so clean_response
# runs fix_box_text → numerify → strip quotes, same as for pred.

def _extract_gold_parts(gt_display: str) -> list[str] | None:
    """Run clean_response on gt_display and return the content split into parts.

    Returns None if no valid boxed span is found.
    """
    cleaned = clean_response(gt_display)
    span    = find_last_boxed_span(cleaned)
    if span is None:
        return None
    content = span[2]   # unquoted, numerified
    # Split on top-level commas to get individual parts (subpart) or single value
    parts = split_top_level_commas(content)
    return parts if parts else None


def compute_reward(completions: list[str], gt_display: list[str],
                   btype: list[str], **kwargs) -> list[float]:
    """Return a binary reward [0.0 or 1.0] for each (completion, gold) pair.

    btype == 'subpart': reward=1 only if ALL parts correct (all-or-nothing).
    btype == 'single' : reward=1 if judger correct.
    btype == 'mcq'    : reward=1 if extracted letter matches gold letter.
    """
    rewards = []
    for completion, gold_disp, bt in zip(completions, gt_display, btype):
        try:
            # ── Step 1: numerify pred ────────────────────────────────────────
            cleaned_pred = clean_response(completion)

            # ── Step 2: numerify gold (gt_display already in \boxed{"..."}) ──
            gold_parts = _extract_gold_parts(gold_disp)
            if gold_parts is None:
                rewards.append(0.0); continue

            if bt == "mcq":
                pred_letter = extract_letter(cleaned_pred)
                gold_letter = extract_letter(clean_response(gold_disp))
                r = 1.0 if (pred_letter and pred_letter == gold_letter) else 0.0

            elif bt == "subpart":
                # gold_parts is already a list of numerified strings
                with contextlib.redirect_stdout(io.StringIO()):
                    ok = bool(judger.auto_judge(
                        pred=cleaned_pred,
                        gold=gold_parts,
                        options=[[]] * len(gold_parts),
                    ))
                r = 1.0 if ok else 0.0

            else:   # 'single'
                with contextlib.redirect_stdout(io.StringIO()):
                    ok = bool(judger.auto_judge(
                        pred=cleaned_pred,
                        gold=[gold_parts[0]],
                        options=[[]],
                    ))
                r = 1.0 if ok else 0.0

        except Exception:
            r = 0.0

        rewards.append(r)

    return rewards


# Quick sanity checks — run after Cell 5 (judger must be loaded)
# gt_display column is already \boxed{"..."} format
_test_cases = [
    # (completion,                              gt_display,                    btype)
    ("The answer is \\boxed{42}",               '\\boxed{"42"}',               "single"),
    ('The answer is \\boxed{"42"}',             '\\boxed{"42"}',               "single"),
    ('The answer is \\boxed{"\\\\frac{1}{2}"}', '\\boxed{"0.5"}',              "single"),
    ('\\boxed{"3","5"}',                        '\\boxed{"3","5"}',            "subpart"),
    ('\\boxed{"B"}',                            '\\boxed{"B"}',                "mcq"),
    # interval — comma inside quotes must not split
    ('\\boxed{"(-8,\\\\infty)"}',               '\\boxed{"(-8,\\\\infty)"}',   "single"),
    # broken box prefix — fix_box_text should repair it
    ('oxed{"42"}',                              '\\boxed{"42"}',               "single"),
]
print("Reward function sanity checks:")
for comp, gd, bt in _test_cases:
    r = compute_reward([comp], [gd], [bt])[0]
    print(f"  {bt:8s}  gold={gd:40s}  reward={r}")

import torch
print(torch.__version__)
!pip install "trl[vllm]"

import inspect
from trl import GRPOConfig
vllm_params = [p for p in inspect.signature(GRPOConfig.__init__).parameters if 'vllm' in p.lower()]
print(vllm_params)

# ═══════════════════════════════════════════════════════════════════════════════
# Cell 7 – GRPO config + trainer
# ═══════════════════════════════════════════════════════════════════════════════
import sys
os.environ["FLASHINFER_DISABLE_VERSION_CHECK"] = "1"
os.environ["PYTORCH_CUDA_ALLOC_CONF"] = "expandable_segments:True"

sys.stdout.fileno = lambda: 1
sys.stderr.fileno = lambda: 2
from trl import GRPOConfig, GRPOTrainer

# ── Hyperparameters ───────────────────────────────────────────────────────────
# With 3000 problems and 1 epoch:
#   Effective batch = per_device_train_batch_size × gradient_accumulation_steps
#   = 2 × 4 = 8 problems per update step
#   Steps per epoch = 3000 / 8 ≈ 375
#   Total steps ≈ 375 × NUM_EPOCHS

NUM_EPOCHS   = 2         # 2 epochs ≈ 750 steps
G            = 4         # group size (completions per prompt for GRPO)
TOTAL_BUDGET = 16384     # total context window — prompt + completion share this budget
# Both are set to TOTAL_BUDGET so TRL never truncates inputs.
# vllm enforces the real cap: it generates min(MAX_COMPLETE, TOTAL_BUDGET - prompt_tokens)
# so the combined total is always ≤ TOTAL_BUDGET.
MAX_PROMPT   = TOTAL_BUDGET
MAX_COMPLETE = TOTAL_BUDGET
VLLM_MAX_LEN = TOTAL_BUDGET

grpo_config = GRPOConfig(
    # ── Output ────────────────────────────────────────────────────────────────
    output_dir=GRPO_CKPT,

    # ── Training schedule ─────────────────────────────────────────────────────
    num_train_epochs=NUM_EPOCHS,
    per_device_train_batch_size=1,      # problems per forward pass
    gradient_accumulation_steps=8,      # effective batch = 8 problems
    learning_rate=5e-6,
    lr_scheduler_type="cosine",
    warmup_ratio=0.05,
    weight_decay=0.01,

    # ── GRPO specifics ────────────────────────────────────────────────────────
    num_generations=G,                  # G completions per prompt
    temperature=0.9,                    # sampling temperature
    max_completion_length=MAX_COMPLETE,
    beta=0.01,                          # KL penalty coefficient (prevents forgetting)

    # ── Generation backend ────────────────────────────────────────────────────
    # use_vllm=False: vllm 0.21.0 (pre-installed) is incompatible with trl 0.14.0's
    # vllm integration. Using HF generate instead — still fast enough on H100.
    use_vllm=True,

    # ── Mixed precision ───────────────────────────────────────────────────────
    bf16=True,
    gradient_checkpointing=True,
    vllm_max_model_length=16384,    # ── Logging & saving ──────────────────────────────────────────────────────
    logging_steps=10,
    save_steps=100,
    save_total_limit=3,
    report_to="none",                   # set to "wandb" if you want W&B logging

    # ── Misc ──────────────────────────────────────────────────────────────────
    seed=42,
    dataloader_num_workers=2,
    remove_unused_columns=False,        # keep gt_raw_json + btype columns
)

trainer = GRPOTrainer(
    model=model,
    args=grpo_config,
    reward_funcs=compute_reward,        # TRL ≥0.9.6: reward_funcs= accepts a callable
    train_dataset=hf_data,
    processing_class=tokenizer,
)

print("Trainer ready ✓")
print(f"  Steps per epoch  : {len(hf_data) // (grpo_config.per_device_train_batch_size * grpo_config.gradient_accumulation_steps)}")
print(f"  Total steps (est): {len(hf_data) // (grpo_config.per_device_train_batch_size * grpo_config.gradient_accumulation_steps) * NUM_EPOCHS}")

# ═══════════════════════════════════════════════════════════════════════════════
# Cell 8 – Train
# ═══════════════════════════════════════════════════════════════════════════════
print("\nStarting GRPO training …")
print("─" * 60)
print(f"  Reward function  : binary (all-or-nothing)")
print(f"  KL coefficient β : {grpo_config.beta}  (prevents catastrophic forgetting)")
print(f"  Group size G     : {G}")
print(f"  Max new tokens   : {MAX_COMPLETE}")
print("─" * 60)

trainer.train(resume_from_checkpoint=True)

# ── Save final adapter ────────────────────────────────────────────────────────
FINAL_DIR = os.path.join(GRPO_CKPT, "final_adapter")
trainer.save_model(FINAL_DIR)
tokenizer.save_pretrained(FINAL_DIR)
print(f"\nFinal adapter saved → {FINAL_DIR}")

# ═══════════════════════════════════════════════════════════════════════════════
# Cell 10 – Merge adapter into base and export (for vllm inference)
# ═══════════════════════════════════════════════════════════════════════════════
"""
Merges the LoRA adapter back into the base weights so you can load the model
directly with vllm or transformers without needing PEFT at inference time.
"""

MERGED_DIR = os.path.join(GRPO_CKPT, "merged_model")
print(f"Merging adapter into base model → {MERGED_DIR}")

_base2 = AutoModelForCausalLM.from_pretrained(
    SFT_CKPT if os.path.isdir(SFT_CKPT) else MODEL_ID,
    torch_dtype=torch.bfloat16, device_map="cpu",  # CPU merge to avoid OOM
    trust_remote_code=True,
)
_peft2   = _PM.from_pretrained(_base2, FINAL_DIR)
_merged  = _peft2.merge_and_unload()
_merged.save_pretrained(MERGED_DIR, safe_serialization=True)
tokenizer.save_pretrained(MERGED_DIR)
print(f"Merged model saved → {MERGED_DIR}")
print("Done.  Load with:  AutoModelForCausalLM.from_pretrained(MERGED_DIR)")

