# -*- coding: utf-8 -*-
"""prepare_rl_data

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1I8BFcMyeDooYEEulpdSgZTdOpwAfgjcL
"""

!pip install -q datasets

from google.colab import drive
drive.mount('/content/drive')

import json, os, re, random
from collections import Counter
from datasets import load_dataset



OUT_DIR  = "/content/drive/MyDrive/CSE 151B/rl_data"
OUT_FILE = os.path.join(OUT_DIR, "rl_data_3000.jsonl")
os.makedirs(OUT_DIR, exist_ok=True)

TARGET_NUMA       = 1100    # NuminaMath multi-part
TARGET_MATH_HARD  = 1100    # MATH Level 4-5
TARGET_MATH_MED   = 600    # MATH Level 3
TARGET_MMLU       = 800    # MMLU MCQ

MATH_DS = "DigitalLearningGmbH/MATH-lighteval"

# ── Cell 3 – Shared helpers ────────────────────────────────────────────────────

def find_all_boxed_spans(text: str):
    """Return list of (start, end, content) for every complete \\boxed{...}."""
    needle = r"\boxed"
    n, spans, i = len(text), [], 0
    while True:
        idx = text.find(needle, i)
        if idx == -1: break
        j = idx + len(needle)
        while j < n and text[j].isspace(): j += 1
        if j >= n or text[j] != "{":
            i = idx + len(needle); continue
        depth, k, sc = 1, j + 1, j + 1
        while k < n and depth > 0:
            ch = text[k]
            if ch == "\\" and k + 1 < n: k += 2; continue
            if ch == "{":   depth += 1
            elif ch == "}":
                depth -= 1
                if depth == 0: break
            k += 1
        if depth == 0:
            spans.append((idx, k + 1, text[sc:k]))
            i = k + 1
        else:
            i = idx + len(needle)
    return spans

# ── Multi-box case detector ───────────────────────────────────────────────────
_CASE_PATTERNS = [
    re.compile(r"\\text\s*\{\s*[Ss]\s*\d"),
    re.compile(r"\\text\s*\{[Cc]ase"),
    re.compile(r"\\text\s*\{[Ii]f\b"),
    re.compile(r"\\text\s*\{[Ww]hen\b"),
    re.compile(r"[a-z]\s*=\s*\d+\s*[,\\].*\\in\b"),
    re.compile(r"\\in\s*\\left"),
    re.compile(r"\\in\s*[\(\[]"),
]
_MAX_PART_LEN = 120

def _is_case_box(content: str) -> bool:
    c = content.strip()
    if len(c) > _MAX_PART_LEN: return True
    return any(p.search(c) for p in _CASE_PATTERNS)

def merge_boxes(solution: str):
    """Returns (merged_or_single_ans, n_boxes, btype).

    btype: 'none' | 'single' | 'subpart' | 'case' | 'mixed'
    Callers skip 'none', 'case', 'mixed'.
    """
    spans = find_all_boxed_spans(solution)
    if not spans:       return "", 0, "none"
    if len(spans) == 1: return spans[0][2].strip(), 1, "single"

    flags = [_is_case_box(s[2]) for s in spans]
    n_case = sum(flags)
    if n_case == len(spans): btype = "case"
    elif n_case > 0:         btype = "mixed"
    else:                    btype = "subpart"

    if btype in ("case", "mixed"):
        return "", len(spans), btype

    contents = [s[2].strip() for s in spans]
    merged   = "\\boxed{" + ",".join(f'"{c}"' for c in contents) + "}"
    return merged, len(spans), "subpart"

# ── Proof filter ──────────────────────────────────────────────────────────────
_PROOF_RE = re.compile(
    r"\b(prove|proof|show\s+that|demonstrate|verify\s+that|establish\s+that"
    r"|show\s+there\s+(exists|is)|find\s+all\s+.{0,40}\s+and\s+prove)\b",
    re.IGNORECASE,
)
def is_proof_question(p: str) -> bool:
    return bool(_PROOF_RE.search(p))

# ── gt_display formatter ───────────────────────────────────────────────────────
def format_gt_display(gt_raw) -> str:
    """Always produce \\boxed{"part1","part2"} with quotes around every part."""
    if isinstance(gt_raw, list):
        return "\\boxed{" + ",".join(f'"{p}"' for p in gt_raw) + "}"
    return f'\\boxed{{"{gt_raw}"}}'

# ── Universal answer-quality filter (all btypes) ──────────────────────────────
_CURRENCY_RE     = re.compile(r'\\[$]|[$€£¥]')
_MCQ_ARTIFACT_RE = re.compile(r'[A-D]\)')          # "C)" leaking into free-response
_DIGIT_WORD_RE   = re.compile(r'\d+\s+[a-zA-Z]{3,}')  # "14 right triangles", "8 km"

def answer_is_clean(gt_raw) -> tuple[bool, str]:
    """Return (True, 'ok') if every part of gt_raw is a clean math value.

    Rejects (returns False) if any part:
      - is empty / whitespace only           → 'empty_part'
      - contains '='  (equation, not value)  → 'has_equals'
      - contains currency ($, €, £ …)        → 'currency'
      - contains \\text{  (English label)    → 'text_label'
      - contains \\!  (forced spacing / time)→ 'forced_spacing'
      - matches [A-D])  (MCQ letter bleed)   → 'mcq_artifact'
      - matches digit+space+3+letters        → 'units_or_label'
        (catches "14 right triangles", "8 p.m.")
    """
    parts = gt_raw if isinstance(gt_raw, list) else [gt_raw]
    for p in parts:
        s = p.strip()
        if not s:                            return False, "empty_part"
        if "=" in s:                         return False, "has_equals"
        if _CURRENCY_RE.search(s):           return False, "currency"
        if r'\text{' in s:                   return False, "text_label"
        if r'\!' in s:                       return False, "forced_spacing"
        if _MCQ_ARTIFACT_RE.search(s):       return False, "mcq_artifact"
        if _DIGIT_WORD_RE.search(s):         return False, "units_or_label"
    return True, "ok"

# ── Multi-part quality filters (Rules 1–3) ────────────────────────────────────
_LONG_WORD_RE  = re.compile(r'[a-zA-Z]{5,}')   # 5+ consecutive letters
_WORD_SPACE_RE = re.compile(r'[a-zA-Z] [a-zA-Z]')  # letter-space-letter (prose)

# Rule 2: banned LaTeX constructs
_BANNED_LATEX_STRS = [
    r'\text{',
    r'\begin{cases}', r'\begin{array}', r'\begin{pmatrix}',
    r'\mid',
    r'\cup', r'\cap',
    r'\mathbb',
]

def _part_is_pure_math(s: str) -> bool:
    """Rule 1: True if s looks like a clean mathematical expression.

    Allows: digits, a-z letters, standard LaTeX commands ≤4 letters
            (\\frac, \\sqrt, \\sin, \\cos, \\pi, \\ln …), operators,
            grouping chars.
    Rejects: any word-like run of 5+ letters (catches \\theta, \\omega,
             \\alpha, English words), or letter-space-letter (prose).
    """
    if _LONG_WORD_RE.search(s):
        return False
    if _WORD_SPACE_RE.search(s):
        return False
    return True

def _part_has_banned_latex(s: str) -> bool:
    """Rule 2: True if s contains layout/set/text LaTeX we want to exclude."""
    if "|" in s:       # catches both \mid and bare | (set-builder notation)
        return True
    return any(b in s for b in _BANNED_LATEX_STRS)

_MAX_PART_CHARS = 30   # Rule 3: single-part length cap
_MAX_PARTS      = 3    # Rule 3: max number of sub-answers

def multipart_passes_filters(contents: list[str]) -> tuple[bool, str]:
    """Apply Rules 1–3 to a list of sub-answer strings.

    Returns (passes: bool, reason: str).
    """
    # Rule 3a: too many parts
    if len(contents) > _MAX_PARTS:
        return False, f"too_many_parts({len(contents)})"
    for part in contents:
        # Rule 3b: individual part too long
        if len(part) > _MAX_PART_CHARS:
            return False, f"part_too_long({len(part)})"
        # Rule 1
        if not _part_is_pure_math(part):
            return False, "not_pure_math"
        # Rule 2
        if _part_has_banned_latex(part):
            return False, "banned_latex"
    return True, "ok"

print("Helpers loaded ✓")

# ── Cell 4 – NuminaMath-CoT (multi-part / subpart only) ───────────────────────
print("\n" + "="*60)
print("SOURCE 1 — NuminaMath-CoT  (multi-part, no proofs)")
print("="*60)
print("Reward policy: all-or-nothing — 0 if any part wrong")

ds_numa = load_dataset("AI-MO/NuminaMath-CoT", split="train")
print(f"Loaded {len(ds_numa):,} total")

numa_records = []
_skip = Counter()

for ex in ds_numa:
    prob = (ex.get("problem") or "").strip()
    sol  = (ex.get("solution") or "").strip()
    if not prob or not sol:   _skip["no_text"]  += 1; continue
    if is_proof_question(prob): _skip["proof"]   += 1; continue

    merged_ans, n_boxes, btype = merge_boxes(sol)

    if btype == "none":               _skip["no_box"]    += 1; continue
    if btype in ("case", "mixed"):    _skip["case_mixed"]  += 1; continue
    if btype == "single":             _skip["single"]    += 1; continue  # multi-part only

    # btype == "subpart" ─────────────────────────────────────────────────────
    spans    = find_all_boxed_spans(sol)
    contents = [s[2].strip() for s in spans]

    # Universal quality filter (empty parts, =, currency, \text{, \!, MCQ artifact, units)
    clean, reason = answer_is_clean(contents)
    if not clean:
        _skip[f"clean_{reason}"] += 1; continue

    # Rules 1–3 (pure-math, banned-latex, length/parts) — multi-part only
    passes, reason = multipart_passes_filters(contents)
    if not passes:
        _skip[f"rule_{reason}"] += 1; continue

    numa_records.append({
        "problem":       prob,
        "options":       None,
        "gt_raw":        contents,                    # list[str]
        "gt_display":    format_gt_display(contents), # \\boxed{"A","B",...}
        "n_parts":       len(contents),
        "btype":         "subpart",
        "reward_policy": "all_or_nothing",
        "source":        f"numinamath_{ex.get('source','unknown')}",
    })

print(f"  subpart collected : {len(numa_records):,}")
print(f"  skipped proof     : {_skip['proof']:,}")
print(f"  skipped case/mixed: {_skip['case_mixed']:,}")
print(f"  skipped single    : {_skip['single']:,}")
print(f"  skipped no_box    : {_skip['no_box']:,}")
for k in sorted(k for k in _skip if k.startswith("clean_") or k.startswith("rule_")):
    print(f"  skipped {k:35s}: {_skip[k]:,}")

if len(numa_records) >= TARGET_NUMA:
    random.shuffle(numa_records)
    numa_records = numa_records[:TARGET_NUMA]
    print(f"  sampled to        : {len(numa_records)}")
else:
    print(f"  WARNING: only {len(numa_records)} found (target {TARGET_NUMA})")

src_dist = Counter(r["source"] for r in numa_records)
print("  sub-source breakdown:")
for src, n in src_dist.most_common(8):
    print(f"    {src:35s} {n}")

# ── Cell 5 – MATH Level 4-5 (hard) ────────────────────────────────────────────
print("\n" + "="*60)
print(f"SOURCE 2 — {MATH_DS}")
print("  Bucket A: Level 4-5  (hard)")
print("="*60)

ds_math = load_dataset(MATH_DS, split="train")
print(f"Loaded {len(ds_math):,} total")
print(f"Fields: {list(ds_math.features.keys())}")

# Show level distribution
lvl_dist = Counter(ex.get("level","?") for ex in ds_math)
print("Level distribution:")
for lvl, n in sorted(lvl_dist.items()):
    print(f"  {lvl:10s} {n:5d}")

def extract_math_record(ex, source_tag: str) -> dict | None:
    """Extract a single clean record from a MATH dataset example."""
    prob = (ex.get("problem") or "").strip()
    sol  = (ex.get("solution") or "").strip()
    if not prob or not sol: return None
    if is_proof_question(prob): return None

    # MATH solutions contain intermediate \boxed{} — always use the LAST one
    spans = find_all_boxed_spans(sol)
    if not spans: return None
    gt_raw = spans[-1][2].strip()
    if not gt_raw: return None

    # Universal quality filter
    clean, _ = answer_is_clean(gt_raw)
    if not clean: return None

    subj = (ex.get("type") or ex.get("subject") or "unknown") \
           .lower().replace(" ", "_")
    return {
        "problem":       prob,
        "options":       None,
        "gt_raw":        gt_raw,
        "gt_display":    format_gt_display(gt_raw),   # \\boxed{"answer"}
        "n_parts":       1,
        "btype":         "single",
        "reward_policy": "all_or_nothing",
        "source":        f"{source_tag}_{subj}",
        "level":         ex.get("level", ""),
    }

math_hard_records = []
for ex in ds_math:
    if ex.get("level") not in {"Level 4", "Level 5"}: continue
    rec = extract_math_record(ex, "math_hard")
    if rec: math_hard_records.append(rec)

print(f"  Level 4-5 after proof filter: {len(math_hard_records):,}")
if len(math_hard_records) > TARGET_MATH_HARD:
    random.shuffle(math_hard_records)
    math_hard_records = math_hard_records[:TARGET_MATH_HARD]
print(f"  Using: {len(math_hard_records)}")

subj_dist = Counter(r["source"] for r in math_hard_records)
print("  Subject breakdown:")
for src, n in subj_dist.most_common():
    print(f"    {src:50s} {n}")

# ── Cell 6 – MATH Level 3 (medium, replaces SciBench) ─────────────────────────
print("\n" + "="*60)
print(f"SOURCE 3 — {MATH_DS}")
print("  Bucket B: Level 3  (medium, replacing SciBench)")
print("="*60)

math_med_records = []
for ex in ds_math:
    if ex.get("level") != "Level 3": continue
    rec = extract_math_record(ex, "math_med")
    if rec: math_med_records.append(rec)

print(f"  Level 3 after proof filter: {len(math_med_records):,}")
if len(math_med_records) > TARGET_MATH_MED:
    random.shuffle(math_med_records)
    math_med_records = math_med_records[:TARGET_MATH_MED]
print(f"  Using: {len(math_med_records)}")

subj_dist = Counter(r["source"] for r in math_med_records)
print("  Subject breakdown:")
for src, n in subj_dist.most_common():
    print(f"    {src:50s} {n}")

# ── Cell 7 – MMLU (MCQ, math + stats) ─────────────────────────────────────────
print("\n" + "="*60)
print("SOURCE 4 — cais/mmlu  (MCQ, math + stats subjects)")
print("="*60)

MMLU_SUBJECTS = [
    "college_mathematics",       #  ~48 problems
    "high_school_statistics",    # ~138 problems
]
# Total available: ~186  (well below TARGET_MMLU=800 — see Cell 8 for adjusted total)
LETTER_MAP = {0: "A", 1: "B", 2: "C", 3: "D"}

mmlu_records = []

for subj in MMLU_SUBJECTS:
    loaded = None
    for split in ["test", "validation", "train"]:
        try:
            loaded = load_dataset("cais/mmlu", subj, split=split)
            break
        except: pass
    if loaded is None:
        print(f"  {subj:40s}: could not load"); continue

    print(f"  {subj:40s}: {len(loaded)} problems")
    for ex in loaded:
        q       = (ex.get("question") or "").strip()
        choices = ex.get("choices") or []
        answer  = ex.get("answer")
        if not q or len(choices) != 4 or answer is None: continue

        letter   = LETTER_MAP.get(int(answer), "A")
        opts     = [f"{LETTER_MAP[i]}. {str(c).strip()}"
                    for i, c in enumerate(choices)]
        full_q   = f"{q}\n\nOptions:\n" + "\n".join(opts)

        # Universal quality filter (rare edge cases, kept for consistency)
        clean, _ = answer_is_clean(letter)
        if not clean: continue

        mmlu_records.append({
            "problem":       full_q,
            "options":       opts,
            "gt_raw":        letter,
            "gt_display":    format_gt_display(letter),   # \\boxed{"A"}
            "n_parts":       1,
            "btype":         "mcq",
            "reward_policy": "all_or_nothing",
            "source":        f"mmlu_{subj}",
        })

print(f"\n  Total MMLU: {len(mmlu_records):,}")
if len(mmlu_records) > TARGET_MMLU:
    random.shuffle(mmlu_records)
    mmlu_records = mmlu_records[:TARGET_MMLU]
print(f"  Using     : {len(mmlu_records)}")

subj_dist = Counter(r["source"] for r in mmlu_records)
print("  Subject breakdown:")
for src, n in subj_dist.most_common():
    print(f"    {src:45s} {n}")

# ── Cell 8 – Combine, shuffle, save ───────────────────────────────────────────
print("\n" + "="*60)
print("COMBINING ALL SOURCES")
print("="*60)

# ── Final quality filters ──────────────────────────────────────────────────────
# Applied to the combined pool.  Each filter checks both problem text and
# gt_raw / gt_display so nothing slips through from any source.

# 1. Matrix / table layout in problem or answer
_MATRIX_RE = re.compile(
    r"\\begin\{(?:p|b|B|v|V|small)?matrix\*?\}"
    r"|\\begin\{(?:cases|array|tabular)\}"
    r"|\\pmatrix|\\bmatrix"
    r"|\\operatorname\{det\}|\\det\s*\{",
    re.IGNORECASE,
)

# 2. Unjudgeable answer patterns (checked on gt_raw parts only)
_ANS_BAD_RE = re.compile(
    r"\\pm|\\mp"                                        # ±  → two values at once
    r"|\\ldots|\\cdots|\\dots"                          # … → sequence / pattern
    r"|\\sum_|\\prod_|\\int(?:[_^]|\s*\\)"              # unresolved Σ / Π / ∫
    r"|\\forall|\\exists"                               # logic quantifiers
    r"|\\Rightarrow|\\Leftrightarrow|\\iff|\\implies"   # logical connectives
    r"|\\(?:long)?(?:right|left)?(?:to|mapsto|rightarrow|leftarrow)"  # f: x → y
    r"|\\\{"                                            # bare set \{1,2,3\}
    r"|\\cup|\\cap"                                     # union/intersection of sets
    r"|\\\\",                                           # double-backslash (broken LaTeX)
)

# 3. Problem needs visual context — Asymptote drawing blocks OR figure references
_VISUAL_RE = re.compile(
    r"\[asy\]"                                          # Asymptote drawing block
    r"|\b(?:figure|diagram|as\s+shown|the\s+graph\s+shows?|"
    r"see\s+(?:the\s+)?(?:figure|diagram|table|graph)|"
    r"the\s+table\s+(?:below|above|shows?)|shown\s+(?:below|above))\b",
    re.IGNORECASE,
)

# 4. True/False questions
_TRUEFALSE_RE = re.compile(r"\btrue\s+or\s+false\b|\bfalse\s+or\s+true\b",
                            re.IGNORECASE)

# 5. Bare comma-separated value list in a single gt_raw part
#    e.g. "0,1,2,3,4" or "20, 38, 380" — multiple values not wrapped in (...) or [...]
#    Allow: thousand-separator numbers like "30,951", LaTeX {,} separators.
def _is_bare_value_list(s: str) -> bool:
    s = s.strip()
    if not s: return False
    if s.startswith(("(", "[", "\\left", "\\{")): return False   # already grouped
    if re.fullmatch(r"[\d\s\{\,\.\-\+]+", s): return False       # plain number with commas
    depth = 0
    for ch in s:
        if ch in "({[": depth += 1
        elif ch in ")}]": depth -= 1
        elif ch == "," and depth == 0:
            return True
    return False


def _final_filter_reject(rec: dict) -> tuple[bool, str]:
    """Return (True, reason) if the record should be dropped."""
    problem  = rec.get("problem", "")
    gt_raw   = rec.get("gt_raw", "")
    gt_parts = gt_raw if isinstance(gt_raw, list) else [gt_raw]
    all_text = [problem, rec.get("gt_display", "")] + gt_parts

    if any(_MATRIX_RE.search(t) for t in all_text if t):
        return True, "matrix"
    if any(_ANS_BAD_RE.search(p) for p in gt_parts if p):
        return True, "bad_answer_pattern"
    if any(_is_bare_value_list(p) for p in gt_parts if p):
        return True, "bare_value_list"
    if _VISUAL_RE.search(problem):
        return True, "needs_visual"
    if _TRUEFALSE_RE.search(problem):
        return True, "true_false"

    return False, ""


all_candidates = numa_records + math_hard_records + math_med_records + mmlu_records
reject_counts  = Counter()
all_records    = []
for rec in all_candidates:
    reject, reason = _final_filter_reject(rec)
    if reject:
        reject_counts[reason] += 1
    else:
        all_records.append(rec)

print(f"  Final filter removed  : {sum(reject_counts.values()):>5} records")
for reason, n in reject_counts.most_common():
    print(f"    {reason:30s}: {n}")

random.shuffle(all_records)
for i, rec in enumerate(all_records):
    rec["id"] = i

print(f"  NuminaMath multi-part (subpart)  : {len(numa_records):>5}")
print(f"  MATH Level 4-5        (single)   : {len(math_hard_records):>5}")
print(f"  MATH Level 3          (single)   : {len(math_med_records):>5}")
print(f"  MMLU MCQ              (mcq)      : {len(mmlu_records):>5}  (college_math + hs_stats only)")
print(f"  {'─'*42}")
print(f"  TOTAL                            : {len(all_records):>5}")
if len(all_records) < 3000:
    print(f"  NOTE: {3000-len(all_records)} slots unused (MMLU capped to 2 subjects)."
          f" Increase TARGET_MATH_HARD/MED to fill if desired.")

btype_dist = Counter(r["btype"] for r in all_records)
print("\nbtype distribution:")
for bt, n in btype_dist.most_common():
    print(f"  {bt:10s} {n:5d}  ({n/len(all_records)*100:.1f}%)")

with open(OUT_FILE, "w", encoding="utf-8") as f:
    for rec in all_records:
        f.write(json.dumps(rec, ensure_ascii=False) + "\n")

print(f"\nSaved → {OUT_FILE}")

# ── Cell 9 – Sanity check ──────────────────────────────────────────────────────
print("\n" + "="*60)
print("SANITY CHECK — one example per btype")
print("="*60)

seen = set()
for rec in all_records:
    bt = rec["btype"]
    if bt in seen: continue
    seen.add(bt)
    print(f"\n── btype={bt}  source={rec['source']} ──")
    print(f"  problem        : {rec['problem'][:200]}")
    if rec.get("options"):
        print(f"  options[:2]    : {rec['options'][:2]}")
    print(f"  gt_raw         : {rec['gt_raw']}")
    print(f"  gt_display     : {str(rec['gt_display'])[:120]}")
    print(f"  n_parts        : {rec['n_parts']}")
    print(f"  reward_policy  : {rec['reward_policy']}")
    if len(seen) == 3: break

print("\n" + "="*60)
print("REWARD POLICY REMINDER (implement in RL training loop)")
print("="*60)
print("""
  For btype == 'subpart'  (NuminaMath multi-part):
    gt_raw is a list, e.g. ["\\\\frac{1}{2}", "3\\\\pi"]
    reward = 1.0  if  judger scores ALL parts correct
    reward = 0.0  if  ANY part is wrong  (no partial credit)

  For btype == 'single'   (MATH):
    gt_raw is a string
    reward = 1.0  if  judger.auto_judge(pred, gold=[gt_raw]) is True
    reward = 0.0  otherwise

  For btype == 'mcq'      (MMLU):
    gt_raw is a letter string, e.g. "B"
    reward = 1.0  if  extract_letter(pred) == gt_raw
    reward = 0.0  otherwise
""")
print("Done. rl_data_3000.jsonl is ready for the RL training loop.")

import json, os

IN_FILE  = "/content/drive/MyDrive/CSE 151B/rl_data/rl_data_3000.jsonl"
OUT_FILE = "/content/drive/MyDrive/CSE 151B/rl_data/id_gt_display.jsonl"

pairs = []
with open(IN_FILE, encoding="utf-8") as f:
    for line in f:
        if line.strip():
            rec = json.loads(line)
            pairs.append({"id": rec["id"], "gt_display": rec["gt_display"]})

with open(OUT_FILE, "w", encoding="utf-8") as f:
    for p in pairs:
        f.write(json.dumps(p, ensure_ascii=False) + "\n")

print(f"Written {len(pairs)} pairs → {OUT_FILE}")
print("Sample:")
for p in pairs[:5]:
    print(f"  {p['id']:>4}  {p['gt_display']}")

import json, os

IN_FILE  = "/content/drive/MyDrive/CSE 151B/rl_data/rl_data_3000.jsonl"
OUT_FILE = "/content/drive/MyDrive/CSE 151B/rl_data/rl_data_3000.jsonl"  # overwrites in place

# ── IDs to delete — fill these in ─────────────────────────────────────────────
DELETE_IDS = {
    241,547,1154,1415,1811,2095,
}
# ──────────────────────────────────────────────────────────────────────────────

records = []
with open(IN_FILE, encoding="utf-8") as f:
    for line in f:
        if line.strip():
            rec = json.loads(line)
            if rec.get("id") not in DELETE_IDS:
                records.append(rec)

# Re-assign IDs so they stay 0-indexed and contiguous after deletion
for i, rec in enumerate(records):
    rec["id"] = i

with open(OUT_FILE, "w", encoding="utf-8") as f:
    for rec in records:
        f.write(json.dumps(rec, ensure_ascii=False) + "\n")

print(f"Deleted {len(DELETE_IDS)} record(s).  {len(records)} remain → {OUT_FILE}")

