# -*- coding: utf-8 -*-
"""private_inference.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12zfFJUbAoib1Ueovhc8lyfVLr-8Q4V96
"""

# !nvcc --version
# !python -c "import torch; print(torch.__version__)"
# !pip show vllm | grep Version
# !pip show vllm
# !ls /usr/local/lib/python3.12/dist-packages/vllm/_C*
# !find / -name "_C.abi3.so" 2>/dev/null

# # # !wget -qO- https://astral.sh/uv/install.sh | sh
# # # !~/.local/bin/uv venv .venv --seed
# # # !.venv/bin/python -m pip install sympy numpy transformers vllm tqdm bitsandbytes antlr4-python3-runtime==4.11.1 ipykernel jupyter
# # # !.venv/bin/python -m ipykernel install --user --name cse151b --display-name "Python (cse151b)"




# # Install uv
# !wget -qO- https://astral.sh/uv/install.sh | sh

# # Create a virtual environment
# !~/.local/bin/uv venv .venv --seed

# # Install dependencies — this is fast thanks to uv's parallel resolver
# !.venv/bin/python -m pip install sympy numpy transformers vllm tqdm bitsandbytes antlr4-python3-runtime==4.11.1 ipykernel jupyter

# # Install Jupyter Kernel
# !.venv/bin/python -m ipykernel install --user --name cse151b --display-name "Python (cse151b)"

# print("Done. Restart the kernel before proceeding.")
# print("Selection process: on top right, click on current kernel '(ususally named python)' -> 'select another kernel' -> 'Jupyter Kernel' -> 'Python (cse151b)'.")
# !find /opt -name "libcudart.so*" 2>/dev/null | head -5
# !find /usr/local/cuda -name "libcudart.so*" 2>/dev/null | head -5
!pip install -q vllm "bitsandbytes>=0.48.1" "antlr4-python3-runtime==4.11.1"
!pip uninstall -y vllm torch torchvision torchaudio
!pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu124
!pip install vllm --extra-index-url https://download.pytorch.org/whl/cu124
# !pip install -q --force-reinstall "bitsandbytes==0.46.1"
# !pip uninstall -y vllm
# !pip install vllm

# !source ./.venv/bin/activate
# from tqdm.auto import tqdm
# import time
# for _ in tqdm(range(5)):
#     time.sleep(0.2)
from google.colab import drive

drive.mount('/content/drive')

# Commented out IPython magic to ensure Python compatibility.
!unzip -q "/content/drive/MyDrive/CSE 151B/151B_SP26_Competition_dsv4_ft.zip" -d /content/
!ls /content/151B_SP26_Competition
# %cd /content/151B_SP26_Competition

!nvidia-smi

MODEL_ID   = "Qwen/Qwen3-4B-Thinking-2507"
#MODEL_ID   = "/content/drive/MyDrive/CSE 151B/checkpoints/opsd_checkpoint/merged_model"
DATA_PATH  = "/content/151B_SP26_Competition/data/private.jsonl"
RESULTS_DIR = "/content/drive/MyDrive/CSE 151B/dv4_pro_ft_submission"

# LoRA — set USE_LORA=False to run the plain base model
USE_LORA   = True
LORA_PATH = "/content/151B_SP26_Competition/deepseekv4-pro/qwen3-4b-sft-lora/checkpoint-396"
  # adapter folder

# Sampling
MAX_TOKENS  = 32768   # max tokens per sample
N_SAMPLES   = 5       # candidates per question (majority / weighted / USC)
CHUNK_SIZE  = 10      # questions per generation batch (H100 can handle 10-20)
GPU_UTIL    = 0.85    # vLLM GPU memory fraction

N_DIGITS    = 10      # decimal digits for numerification
WORK_PREC   = N_DIGITS + 6

import csv, gc, json, math, os, re, sys, shutil
from collections import Counter, defaultdict
from pathlib import Path
from typing import Optional

import sympy as sp
from sympy.parsing.latex import parse_latex
import math as _math

from transformers import AutoTokenizer
from vllm import LLM, SamplingParams
from vllm.lora.request import LoRARequest
import ninja
from tqdm import tqdm

os.environ["CUDA_VISIBLE_DEVICES"] = "0"
os.environ["VLLM_USE_FLASHINFER_SAMPLER"] = "0"
os.makedirs(RESULTS_DIR, exist_ok=True)

# Checkpoint file — stores all three voting results so retries are safe
CHECKPOINT_PATH = os.path.join(RESULTS_DIR, "checkpoint.jsonl")

data = [json.loads(line) for line in open(DATA_PATH)]
n_mcq  = sum(bool(d.get("options")) for d in data)
n_free = len(data) - n_mcq
print(f"Loaded {len(data)} questions  ({n_mcq} MCQ, {n_free} free-form)")

SYSTEM_PROMPT_MATH = r"""You are an expert mathematician. Reason as deeply as needed, then output ONLY the final boxed answer — no explanation, no working, no preamble.

## Classify each sub-answer before writing it

**Category 1 — Discrete count.** The answer counts INDIVISIBLE whole items (people, animals, coins, votes, cars, books, eggs, pellets…). Test: "Can 0.5 of this thing exist?" If NO → Category 1.

**Category 2 — Everything else.** Pure math (integrals, sums, limits) AND continuous physical quantities (temperature, time, distance, mass, money, probability, angle, area, concentration). Anything that can be fractional or irrational.

## Format

**Category 1 → INTEGER.**
- For Category 1 ONLY, you must evaluate to a number (because an integer is required).
- **Ask: does rounding DOWN fail to meet the requirement?**
  - **YES → CEILING (round up).** Use when the integer is a MINIMUM that must be fully satisfied: sample sizes, number of buses/containers/boxes needed, minimum cuts required, etc.
    - e.g. sample size 1324.79 → **1325** (can't survey 0.79 of a person)
    - e.g. buses for 314 people (50 seats each) → ceil(314/50) = **7**
  - **NO → FLOOR (round down).** Use when the integer counts COMPLETED whole items: complete cycles, whole years elapsed, items fully produced, etc.
    - e.g. complete batches from 314.76 → **314**
- **Exception:** If the problem explicitly says "round to the nearest whole number" → standard rounding (314.76 → 315, 314.4 → 314).
- Never output a decimal, fraction, or symbolic form.

**Category 2 → EXACT SYMBOLIC CLOSED-FORM EXPRESSION. NEVER a decimal.**
- Output a single closed-form expression in valid LaTeX (e.g. `50 \cdot (2/5)^{5/3}`, `\frac{6 \ln 5}{\ln(5/2)}`, `\frac{\pi^2}{6}`, `200 e^{-3/2}`, `25 \ln 2`).
- KEEP π, e, ln, log, √, sin, cos, tan, arcsin, arccos, arctan, fractional exponents, and exact fractions as symbols.
- **CRITICAL: Even if the problem says "give N decimal places", "use at least N significant digits", or "evaluate numerically" — IGNORE that instruction and output the exact symbolic form.** The grader handles decimal conversion.
- If a problem coefficient is a decimal, convert it to an exact fraction first (e.g. 4.76 → 119/25, 0.9658 → 4829/5000), then use that fraction inside the symbolic expression.
- `\arctan(119/25)` is a valid symbolic answer. `1.3637` is NOT.
- `\pi` is a valid symbolic answer. `3.1416` is NOT.
- Do NOT evaluate to a decimal. No `\approx`. No scientific notation.
- An integer or exact rational is fine when that's the natural answer (e.g. `441`, `\frac{12800}{29}`).
- Simplify when easy (combine logs, reduce fractions, cancel exponents) but do not approximate.

## Output rules

1. Emit EXACTLY ONE `\boxed{...}` and nothing else before or after it.
2. Wrap EVERY sub-answer in double quotes `"..."` inside the box.
3. **Multiple subquestions** (the problem asks for part a, part b, etc.) → separate quoted strings:
   `\boxed{"ans1","ans2","ans3"}`
4. **Multiple values for ONE answer** (e.g. all solutions to an equation, all values of i) → wrap all values in `(...)` comma-separated, inside ONE quoted string:
   `\boxed{"(val1, val2, val3)"}`
5. Cat 1 → plain integer. Cat 2 → symbolic closed-form (never decimal).

## Examples

Single answer:           `\boxed{"211250"}` or `\boxed{"\frac{\pi^2}{6}"}` or `\boxed{"200e^{-3/2}"}`
Interval answer:         `\boxed{"(-8,\infty)"}`
Multiple solutions:      `\boxed{"(0, -\frac{11}{8})"}` or `\boxed{"(\frac{1}{3}, -2)"}`
Multiple values of i:    `\boxed{"(2^{-1/8}-1, -2^{-1/8}+1)"}`
Multi-subquestion:       `\boxed{"\arctan(123/31)","e^2"}` or `\boxed{"(50(2/5)^{5/3},50(2/13)^{4/3})","\frac{6\ln5}{\ln(5/2)}"}`
Multi-select MCQ:        `\boxed{"B, C, E, G"}`
Single letter MCQ:       `\boxed{"C"}`
"""

SYSTEM_PROMPT_MCQ = (
    "You are an expert mathematician. Reason as deeply as needed"
    "CRITICAL: Your ENTIRE response must be exactly one token: \\boxed{X} where X is the correct letter."
    " No explanation. No working. No preamble. Just \\boxed{X}."
    " Example of a complete valid response: \\boxed{C}"
    " If your computed answer matches no option, pick the closest. Still output only \\boxed{X}."
)
SYSTEM_PROMPT_USC = (
    "You are a mathematical judge. You will be given a math problem and a list of candidate answers. "
    "Select the single most likely correct answer from the list. "
    "Reply with ONLY \\boxed{answer}, copying the answer exactly as it appears in the list."
)

def build_prompt(question: str, options: Optional[list]) -> tuple[str, str]:
    """Return (system_prompt, user_message) for a question."""
    if options:
        labels    = [chr(65 + i) for i in range(len(options))]
        opts_text = "\n".join(f"{lbl}. {opt.strip()}" for lbl, opt in zip(labels, options))
        return SYSTEM_PROMPT_MCQ, f"{question}\n\nOptions:\n{opts_text}"
    return SYSTEM_PROMPT_MATH, question


def build_usc_prompt(question: str, options: Optional[list], candidates: list[str]) -> tuple[str, str]:
    """Return (system_prompt, user_message) for USC candidate selection."""
    cand_text = "\n".join(f"{i + 1}. {c}" for i, c in enumerate(candidates))
    if options:
        labels    = [chr(65 + i) for i in range(len(options))]
        opts_text = "\n".join(f"{lbl}. {opt.strip()}" for lbl, opt in zip(labels, options))
        user = f"Problem: {question}\n\nOptions:\n{opts_text}\n\nCandidates:\n{cand_text}"
    else:
        user = f"Problem: {question}\n\nCandidates:\n{cand_text}"
    return SYSTEM_PROMPT_USC, user

import transformers
# Fake the new attribute expected by transformers 4.51.0+ for Qwen3's tokenizer
transformers.PreTrainedTokenizerBase.all_special_tokens_extended = property(lambda self: self.all_special_tokens)
tokenizer = AutoTokenizer.from_pretrained(MODEL_ID)
tokenizer.pad_token = tokenizer.eos_token

# Suppress vLLM's fileno complaints inside Colab
sys.stdout.fileno = lambda: 1
sys.stderr.fileno = lambda: 2

llm = LLM(
    model=MODEL_ID,
    enable_lora=USE_LORA,
    max_lora_rank=32 if USE_LORA else None,
    max_loras=1      if USE_LORA else None,
    enable_prefix_caching=False,
    gpu_memory_utilization=GPU_UTIL,
    max_model_len=MAX_TOKENS,
    trust_remote_code=True,
    max_num_seqs=256,
    max_num_batched_tokens=MAX_TOKENS,
)

lora_request = LoRARequest("sft", 1, LORA_PATH) if USE_LORA else None

sampling_params = SamplingParams(
    max_tokens=MAX_TOKENS,
    temperature=0.85,
    top_p=0.95,
    top_k=20,
    min_p=0.0,
    presence_penalty=0.0,
    repetition_penalty=1.0,
    n=N_SAMPLES,
    logprobs=1,
)

usc_sampling_params = SamplingParams(
    max_tokens=1024,   # USC only needs to pick from a short list
    temperature=0.0,   # greedy — deterministic selection
    n=1,
)

print(f"Model loaded.  LoRA={'ON  → ' + LORA_PATH if USE_LORA else 'OFF'}")

# ── Section 5 – Numerification Helpers ───────────────────────────────────────
# Pipeline: raw_text → fix_box_text → numerify_response
# fix_box must come first — a broken "oxed{E}" prevents find_last_boxed_span
# from locating the answer, so numerification would be a no-op.


def find_last_boxed_span(text: str):
    """Return (start, end, content) of the last complete \\boxed{...}, or None."""
    if not text:
        return None
    needle, n, last, i = r"\boxed", len(text), None, 0
    while True:
        idx = text.find(needle, i)
        if idx == -1:
            break
        j = idx + len(needle)
        while j < n and text[j].isspace():
            j += 1
        if j >= n or text[j] != "{":
            i = idx + len(needle)
            continue
        depth, k, start_content = 1, j + 1, j + 1
        while k < n and depth > 0:
            ch = text[k]
            if ch == "\\" and k + 1 < n:
                k += 2; continue
            if ch == "{":   depth += 1
            elif ch == "}":
                depth -= 1
                if depth == 0: break
            k += 1
        if depth == 0:
            last = (idx, k + 1, text[start_content:k])
            i = k + 1
        else:
            i = idx + len(needle)
    return last


_BOXED_RE = re.compile(r"\\?b?oxed\s*\{", re.IGNORECASE)


def find_last_balanced_boxed(text: str):
    """Find the last \\boxed{} even when the leading \\ or 'b' is missing."""
    last = None
    for m in _BOXED_RE.finditer(text):
        if "oxed{" not in m.group().replace(" ", ""):
            continue
        brace_open = m.end() - 1
        depth, i, n = 1, brace_open + 1, len(text)
        while i < n and depth > 0:
            ch = text[i]
            if ch == "\\" and i + 1 < n: i += 2; continue
            if ch == "{": depth += 1
            elif ch == "}":
                depth -= 1
                if depth == 0: break
            i += 1
        if depth == 0:
            last = (m.start(), i + 1, text[brace_open + 1:i])
    return last


def fix_box_text(text: str) -> str:
    """Normalize the last boxed expression to \\boxed{...}.

    Must run BEFORE numerify_response — a broken 'oxed{E}' is invisible
    to find_last_boxed_span, so numerification would silently do nothing.
    """
    span = find_last_balanced_boxed(text)
    if span is None:
        return text
    start, end, inner = span
    correct = "\\boxed{" + inner + "}"
    if text[start:end] == correct:
        return text
    return text[:start] + correct + text[end:]


def split_top_level_commas(s: str):
    """Split on commas not inside any brace or paren (handles \\left...\\right)."""
    out, depth, start, i, n = [], 0, 0, 0, len(s)
    while i < n:
        ch = s[i]
        if ch == "\\" and i + 1 < n: i += 2; continue
        if ch in "{(":   depth += 1
        elif ch in "})": depth -= 1
        elif ch == "," and depth == 0:
            out.append(s[start:i]); start = i + 1
        i += 1
    out.append(s[start:])
    return [p.strip() for p in out if p.strip()]


def split_quoted_answers(content: str):
    """Split \\boxed{"ans1","ans2"} content on commas outside double-quotes.
    Returns list of unquoted strings, or None if no quotes present."""
    content = content.strip()
    if '"' not in content:
        return None
    parts, current, in_q = [], [], False
    for ch in content:
        if ch == '"':
            in_q = not in_q
        elif ch == ',' and not in_q:
            p = ''.join(current).strip()
            if p: parts.append(p)
            current = []
        else:
            current.append(ch)
    p = ''.join(current).strip()
    if p: parts.append(p)
    return parts or None


def compress_letter_list(s: str) -> str:
    """'A, B, C' → 'ABC' for multi-select MCQ answers."""
    parts = [p.strip() for p in s.split(',')]
    if len(parts) > 1 and all(re.fullmatch(r'[A-Za-z]', p) for p in parts):
        return ''.join(p.upper() for p in parts)
    return s


_CLEANUPS = [
    (r"\\dfrac",             r"\\frac"),
    (r"\\tfrac",             r"\\frac"),
    (r"\\!",                 ""),
    (r"\\,",                 ""),
    (r"\\;",                 ""),
    (r"\\ ",                 ""),
    (r"\\\\ ",               " "),
    (r"\\left",              ""),
    (r"\\right",             ""),
    (r"\\$",                 ""),
    (r"\\%",                 ""),
    (r"\\text\{([^}]*)\}",   r"\1"),   # \text{C} → C
]


def _clean_latex(s: str) -> str:
    """Strip cosmetic LaTeX and convert degree notation to radian decimals."""
    s = s.strip()

    def _deg2rad(m):
        return "{" + str(_math.radians(float(m.group(1)))) + "}"

    s = re.sub(r"(\d+(?:\.\d+)?)\s*\^(\{)?\\circ(?(2)\})", _deg2rad, s)
    s = re.sub(r"(\d+(?:\.\d+)?)\s*°",                      _deg2rad, s)
    for pat, rep in _CLEANUPS:
        s = re.sub(pat, rep, s)
    return re.sub(r"^=\s*", "", s).strip()


def _format_numeric(val, n_digits: int) -> str:
    """Format a sympy numeric value — handles real, complex, and infinity."""
    re_part, im_part = val.as_real_imag()
    re_f, im_f = float(re_part), float(im_part)
    if _math.isinf(re_f):
        return "\\infty" if re_f > 0 else "-\\infty"
    if abs(im_f) < 1e-12:
        return f"{re_f:.{n_digits}f}"
    sign = "+" if im_f >= 0 else ""
    return f"{re_f:.{n_digits}f}{sign}{im_f:.{n_digits}f}i"


def _sub_stat_quantiles(s: str) -> str:
    """Replace z_α, chi²_{α,df}, t_{α,df}, F_{α,df1,df2} with decimal values
    before passing to parse_latex, so surrounding expressions can evaluate."""
    try:
        from scipy import stats as _sc

        s = re.sub(r"\bz\s*_\{?\s*([0-9.]+)\s*\}?",
                   lambda m: str(_sc.norm.ppf(1 - float(m.group(1)))), s)
        s = re.sub(r"\\?chi\^?2\s*_\{?\s*([0-9.]+)\s*,\s*([0-9]+)\s*\}?",
                   lambda m: str(_sc.chi2.ppf(1 - float(m.group(1)), int(m.group(2)))),
                   s, flags=re.IGNORECASE)
        s = re.sub(
            r"\bt\s*_\{?\s*([0-9.]+)\s*,\s*\\frac\{([0-9]+)\}\{([0-9]+)\}\s*\}?",
            lambda m: str(_sc.t.ppf(1 - float(m.group(1)),
                                    float(m.group(2)) / float(m.group(3)))), s)
        s = re.sub(r"\bt\s*_\{?\s*([0-9.]+)\s*,\s*([0-9.]+)\s*\}?",
                   lambda m: str(_sc.t.ppf(1 - float(m.group(1)), float(m.group(2)))), s)
        s = re.sub(r"\bF\s*_\{?\s*([0-9.]+)\s*,\s*([0-9]+)\s*,\s*([0-9]+)\s*\}?",
                   lambda m: str(_sc.f.ppf(1 - float(m.group(1)),
                                           int(m.group(2)), int(m.group(3)))), s)
    except ImportError:
        pass
    return s


def _eval_cdf_expression(s: str, n_digits: int, _depth: int = 0):
    r"""Evaluate \Phi(x), \Phi^{-1}(p), \Pr(T_n < x). Returns str or None."""
    if "\\Phi" not in s and "\\Pr" not in s:
        return None
    try:
        from scipy import stats as _sc

        def _inner(expr):
            if _depth >= 2: return None
            try: return float(evaluate_piece(expr.strip(), n_digits, _depth + 1))
            except: return None

        w = s
        w = re.sub(r"\\Phi\s*\^\{-1\}\s*\(([^)]+)\)",
                   lambda m: (f"{_sc.norm.ppf(v):.{n_digits}f}"
                              if (v := _inner(m.group(1))) is not None else m.group(0)), w)
        w = re.sub(r"\\Phi\s*\(([^)]+)\)",
                   lambda m: (f"{_sc.norm.cdf(v):.{n_digits}f}"
                              if (v := _inner(m.group(1))) is not None else m.group(0)), w)
        w = re.sub(r"\\Pr\s*\(\s*T_\{?(\d+)\}?\s*<\s*([^)]+)\)",
                   lambda m: (f"{_sc.t.cdf(_inner(m.group(2)), _inner(m.group(1))):.{n_digits}f}"
                              if _inner(m.group(1)) is not None else m.group(0)), w)

        if w == s: return None
        try: return f"{float(w):.{n_digits}f}"
        except: pass
        try:
            val = sp.N(sp.sympify(w), WORK_PREC)
            return _format_numeric(val, n_digits)
        except: pass
        return w
    except: return None


def evaluate_piece(piece: str, n_digits: int = N_DIGITS, _depth: int = 0) -> str:
    """Convert one boxed sub-answer to an N-digit decimal string."""
    p = (piece or "").strip()
    if not p: return p
    if re.fullmatch(r"[A-Z]", p): return p          # MCQ letter — never parse
    if re.fullmatch(r"-?\d+", p): return p           # plain integer
    if re.fullmatch(r"-?\d+\.\d+", p):
        try: return f"{float(p):.{n_digits}f}"
        except: pass

    s = _clean_latex(p)
    if re.fullmatch(r"[A-Z]+", s): return s          # \text{C} → C after cleaning

    s = _sub_stat_quantiles(s)

    cdf = _eval_cdf_expression(s, n_digits, _depth)
    if cdf is not None: return cdf

    try:
        expr = parse_latex(s)
        if isinstance(expr, sp.Eq): expr = expr.rhs  # x = -1/2 → extract RHS
        expr = expr.subs([(sp.Symbol('pi'), sp.pi),
                          (sp.Symbol('e'),  sp.E),
                          (sp.Symbol('i'),  sp.I)])
        return _format_numeric(sp.N(expr, WORK_PREC), n_digits)
    except Exception as e:
        pass  # silently try fallback

    try:
        expr = sp.sympify(s.replace("\\", ""))
        return _format_numeric(sp.N(expr, WORK_PREC), n_digits)
    except: pass

    # scipy last-resort for standalone statistical symbols
    try:
        from scipy import stats as _sc
        m = re.search(r"chi\^?2\s*_\{?\s*([0-9.]+)\s*,\s*([0-9]+)\s*\}?", p, re.I)
        if m: return f"{_sc.chi2.ppf(1-float(m.group(1)),int(m.group(2))):.{n_digits}f}"
        m = re.search(r"[Ff]\s*_\{?\s*([0-9.]+)\s*,\s*([0-9]+)\s*,\s*([0-9]+)\s*\}?", p)
        if m: return f"{_sc.f.ppf(1-float(m.group(1)),int(m.group(2)),int(m.group(3))):.{n_digits}f}"
        m = re.search(r"\bt\s*_\{?\s*([0-9.]+)\s*,\s*([0-9]+)\s*\}?", p)
        if m: return f"{_sc.t.ppf(1-float(m.group(1)),float(m.group(2))):.{n_digits}f}"
        m = re.search(r"\bz\s*_\{?\s*([0-9.]+)\s*\}?", p)
        if m: return f"{_sc.norm.ppf(1-float(m.group(1))):.{n_digits}f}"
    except: pass

    return p  # give up — return original


def numerify_paren_list(s: str, n_digits: int = N_DIGITS) -> str:
    """Numerify a sub-answer that may be a parenthesised value list."""
    inner = re.sub(r"\\left\s*", "", s.strip())
    inner = re.sub(r"\\right\s*", "", inner).strip()
    if inner.startswith('(') and inner.endswith(')'):
        parts = split_top_level_commas(inner[1:-1])
        if len(parts) > 1:
            return '(' + ', '.join(evaluate_piece(p, n_digits) for p in parts) + ')'
    return evaluate_piece(s, n_digits)


def numerify_response(text: str, n_digits: int = N_DIGITS) -> str:
    """Numerify the last \\boxed{} in-place. Handles quoted and legacy formats.

    Call AFTER fix_box_text — requires a well-formed \\boxed{}.
    """
    try:
        span = find_last_boxed_span(text)
        if span is None: return text
        start, end, content = span

        quoted = split_quoted_answers(content)
        if quoted is not None:
            new_parts = [numerify_paren_list(compress_letter_list(p), n_digits)
                         for p in quoted]
            new_box = "\\boxed{" + ",".join(f'"{p}"' for p in new_parts) + "}"
            return text[:start] + new_box + text[end:]

        parts = split_top_level_commas(content)
        if not parts: return text
        new_box = "\\boxed{" + ", ".join(numerify_paren_list(p, n_digits)
                                         for p in parts) + "}"
        return text[:start] + new_box + text[end:]
    except:
        return text

# ── Section 6 – Voting Functions ──────────────────────────────────────────────

def extract_letter(text: str) -> str:
    m = re.search(r"\\boxed\{([A-Za-z])\}", text or "")
    if m: return m.group(1).upper()
    matches = re.findall(r"\b([A-Z])\b", (text or "").upper())
    return matches[-1] if matches else ""


def extract_boxed(text: str) -> str:
    span = find_last_boxed_span(text or "")
    return span[2] if span else ""


def vote_key(text: str, is_mcq: bool) -> str:
    """Canonical vote key: letter for MCQ, numerified boxed content for free-form.
    Using the numerified decimal string is faster and more reliable than sympy
    canonicalization, which can fail on many valid LaTeX expressions."""
    return extract_letter(text) if is_mcq else extract_boxed(text)


def majority_vote(samples: list[dict], is_mcq: bool) -> str:
    """Pick the response whose vote key appears most often."""
    counter, best = Counter(), {}
    for s in samples:
        key = vote_key(s["numerified"], is_mcq)
        if not key: continue
        counter[key] += 1
        best.setdefault(key, s["numerified"])
    if not counter: return samples[0]["numerified"] if samples else ""
    return best[counter.most_common(1)[0][0]]


def weighted_vote(samples: list[dict], is_mcq: bool) -> str:
    """Like majority_vote but each vote is weighted by the sample's normalised
    log-probability: weight = exp(cumulative_logprob / n_tokens).
    A response the model is more confident about counts more."""
    weights, best = defaultdict(float), {}
    for s in samples:
        key = vote_key(s["numerified"], is_mcq)
        if not key: continue
        weights[key] += s["weight"]
        if key not in best or s["weight"] > best.get("_w_" + key, -1e9):
            best[key]        = s["numerified"]
            best["_w_" + key] = s["weight"]
    if not weights: return samples[0]["numerified"] if samples else ""
    winner = max(weights, key=weights.__getitem__)
    return best[winner]


def usc_select(question: str, options: Optional[list],
               samples: list[dict], is_mcq: bool,
               llm_inst=None) -> str:          # ← add llm_inst param
    """Universal Self-Consistency: ask the model to choose the best answer
    from the unique candidates produced by the N samples.

    If all samples agree, skips the LLM call and returns the shared answer.
    """
    unique_keys   = list(dict.fromkeys(
        vote_key(s["numerified"], is_mcq) for s in samples
        if vote_key(s["numerified"], is_mcq)
    ))
    key_to_sample = {vote_key(s["numerified"], is_mcq): s["numerified"]
                     for s in samples
                     if vote_key(s["numerified"], is_mcq)}

    if len(unique_keys) <= 1:
        return majority_vote(samples, is_mcq)

    system, user = build_usc_prompt(question, options, unique_keys)
    prompt = tokenizer.apply_chat_template(
        [{"role": "system", "content": system},
         {"role": "user",   "content": user}],
        tokenize=False,
        add_generation_prompt=True,
        enable_thinking=True,
    )
    _llm = llm_inst if llm_inst is not None else llm   # ← use passed-in or global
    out  = _llm.generate([prompt], usc_sampling_params,
                         lora_request=lora_request)[0].outputs[0].text.strip()
    fixed   = fix_box_text(out)
    num     = numerify_response(fixed)
    sel_key = vote_key(num, is_mcq)

    if sel_key in key_to_sample:
        return key_to_sample[sel_key]
    return majority_vote(samples, is_mcq)

# ── Section 7 – Main Generation Loop ─────────────────────────────────────────

# Load already-completed IDs from checkpoint
completed_ids = set()
if os.path.exists(CHECKPOINT_PATH):
    with open(CHECKPOINT_PATH, encoding="utf-8") as f:
        for line in f:
            if line.strip():
                try: completed_ids.add(str(json.loads(line)["id"]))
                except: pass

remaining = [item for item in data if str(item.get("id")) not in completed_ids]
print(f"Completed: {len(completed_ids)}  |  Remaining: {len(remaining)}")

if remaining:
    num_chunks = (len(remaining) + CHUNK_SIZE - 1) // CHUNK_SIZE

    for chunk_idx in range(num_chunks):
        chunk = remaining[chunk_idx * CHUNK_SIZE : (chunk_idx + 1) * CHUNK_SIZE]
        print(f"\n── Chunk {chunk_idx + 1}/{num_chunks}  "
              f"(items {chunk_idx*CHUNK_SIZE+1}–{chunk_idx*CHUNK_SIZE+len(chunk)}) ──")

        # ── A. Build prompts ──────────────────────────────────────────────────
        prompts = []
        for item in chunk:
            system, user = build_prompt(item["question"], item.get("options"))
            prompts.append(tokenizer.apply_chat_template(
                [{"role": "system", "content": system},
                 {"role": "user",   "content": user}],
                tokenize=False,
                add_generation_prompt=True,
                enable_thinking=True,
            ))

        # ── B. Generate N samples per question ───────────────────────────────
        gen_outputs = llm.generate(prompts, sampling_params,
                                   lora_request=lora_request)

        # ── C. Per question: fix_box → numerify → build sample dicts ─────────
        #   fix_box MUST come before numerify (broken "oxed{E}" is invisible
        #   to find_last_boxed_span, so numerify would be a no-op otherwise).
        all_samples = []   # list[list[dict]]  shape: (chunk_size, N_SAMPLES)
        for result in gen_outputs:
            q_samples = []
            for out in result.outputs:
                raw    = out.text.strip()
                fixed  = fix_box_text(raw)
                num    = numerify_response(fixed)
                # Length-normalised log-prob → probability weight for weighted vote
                lp     = out.cumulative_logprob
                norm_lp = lp / max(len(out.token_ids), 1) if lp is not None else 0.0
                weight  = math.exp(norm_lp)
                q_samples.append({
                    "fixed":      fixed,       # box-corrected full response
                    "numerified": num,         # numerified for voting keys
                    "weight":     weight,      # for weighted vote
                })
            all_samples.append(q_samples)

        # ── D. USC prompts (one per question with >1 unique candidate) ────────
        usc_results = []
        for item, samples in zip(chunk, all_samples):
            usc_results.append(
                usc_select(item["question"], item.get("options"),
                           samples, bool(item.get("options")))
            )

        # ── E. Compute all three voting results & save checkpoint ─────────────
        with open(CHECKPOINT_PATH, "a", encoding="utf-8") as f:
            for item, samples, usc_resp in zip(chunk, all_samples, usc_results):
                is_mcq = bool(item.get("options"))
                record = {
                    "id":               item.get("id"),
                    "is_mcq":           is_mcq,
                    "response_majority": majority_vote(samples, is_mcq),
                    "response_weighted": weighted_vote(samples, is_mcq),
                    "response_usc":      usc_resp,
                }
                f.write(json.dumps(record, ensure_ascii=False) + "\n")

        print(f"  ✓ chunk {chunk_idx + 1} saved")

    print("\nAll chunks complete.")
else:
    print("Nothing to do — all questions already in checkpoint.")

# ── Section 8 – Export Submission CSVs ───────────────────────────────────────
# Reads the checkpoint and writes one CSV per voting method.
# Choose the best-performing one to submit to Kaggle.

records = []
with open(CHECKPOINT_PATH, encoding="utf-8") as f:
    for line in f:
        if line.strip():
            try: records.append(json.loads(line))
            except: pass

records.sort(key=lambda r: (r["id"] is None, r["id"]))

def write_submission(records: list[dict], key: str, out_path: str):
    """Write a submission CSV using the given response key."""
    with open(out_path, "w", encoding="utf-8", newline="") as fcsv:
        w = csv.writer(fcsv, quoting=csv.QUOTE_MINIMAL)
        w.writerow(["id", "response"])
        for r in records:
            w.writerow([r["id"], r.get(key, "")])
    print(f"  wrote {out_path}  ({len(records)} rows)")

print("\nExporting submission CSVs:")
write_submission(records, "response_majority",
                 os.path.join(RESULTS_DIR, "submission_majority.csv"))
write_submission(records, "response_weighted",
                 os.path.join(RESULTS_DIR, "submission_weighted.csv"))
write_submission(records, "response_usc",
                 os.path.join(RESULTS_DIR, "submission_usc.csv"))

# ── Section 9 – Retry (truncated / missing records) ──────────────────────────
_retry_llm_ready = False
_retry_llm = None
def run_retry(max_model_len: int = 65536, max_tokens: int = 60000,
              n_samples: int = 5):
    """Re-run any IDs not yet in the checkpoint or whose response has no boxed answer."""
    global llm,_retry_llm_ready

    covered = set()
    with open(CHECKPOINT_PATH, encoding="utf-8") as f:
        for line in f:
            if line.strip():
                try:
                    r = json.loads(line)
                    # Only count as covered if at least one voting result has a box
                    if any(find_last_balanced_boxed(r.get(k, ""))
                           for k in ("response_majority", "response_weighted", "response_usc")):
                        covered.add(str(r["id"]))
                except: pass

    missing = [item for item in data if str(item.get("id")) not in covered]
    print(f"[retry] {len(missing)} records to retry")
    if not missing:
        print("[retry] Nothing to do.")
        return

    # Rebuild LLM with larger context
    if not _retry_llm_ready:
        del llm; gc.collect(); __import__("torch").cuda.empty_cache()
        import os
        import sys

        # Apply the patch
        sys.stdout.fileno = lambda: 1
        sys.stderr.fileno = lambda: 2
        tokenizer = AutoTokenizer.from_pretrained(MODEL_ID)
        tokenizer.pad_token = tokenizer.eos_token
        _retry_llm = LLM(
            model=MODEL_ID,
            enable_lora=USE_LORA,
            max_lora_rank=32 if USE_LORA else None,
            max_loras=1      if USE_LORA else None,
            enable_prefix_caching=False,
            gpu_memory_utilization=0.90,
            max_model_len=max_model_len,
            trust_remote_code=True,
            max_num_seqs=64,
            max_num_batched_tokens=max_model_len,
            enforce_eager=True,
        )
        _retry_llm_ready = True
        print("[retry] LLM ready ✓")
    else:
        print("[retry] Reusing existing retry LLM ✓")

    retry_params = SamplingParams(
        max_tokens=max_tokens, temperature=0.85,
        top_p=0.95, top_k=20, n=n_samples,logprobs=1,
    )

    num_chunks = (len(missing) + CHUNK_SIZE - 1) // CHUNK_SIZE
    for chunk_idx in range(num_chunks):
        chunk = missing[chunk_idx * CHUNK_SIZE : (chunk_idx + 1) * CHUNK_SIZE]
        print(f"[retry] chunk {chunk_idx + 1}/{num_chunks}")

        prompts = []
        for item in chunk:
            system, user = build_prompt(item["question"], item.get("options"))
            prompts.append(tokenizer.apply_chat_template(
                [{"role": "system", "content": system},
                 {"role": "user",   "content": user}],
                tokenize=False, add_generation_prompt=True, enable_thinking=True,
            ))

        gen_outputs = _retry_llm.generate(prompts, retry_params,
                                         lora_request=lora_request)
        all_samples = []
        for result in gen_outputs:
            q_samples = []
            for out in result.outputs:
                fixed  = fix_box_text(out.text.strip())
                num    = numerify_response(fixed)
                lp     = out.cumulative_logprob
                norm_lp = lp / max(len(out.token_ids), 1) if lp is not None else 0.0
                q_samples.append({"fixed": fixed, "numerified": num,
                                   "weight": math.exp(norm_lp)})
            all_samples.append(q_samples)

        usc_results = [
            usc_select(item["question"], item.get("options"),
                       samples, bool(item.get("options")),llm_inst=_retry_llm)
            for item, samples in zip(chunk, all_samples)
        ]

        with open(CHECKPOINT_PATH, "a", encoding="utf-8") as f:
            for item, samples, usc_resp in zip(chunk, all_samples, usc_results):
                is_mcq = bool(item.get("options"))
                f.write(json.dumps({
                    "id":                item.get("id"),
                    "is_mcq":           is_mcq,
                    "response_majority": majority_vote(samples, is_mcq),
                    "response_weighted": weighted_vote(samples, is_mcq),
                    "response_usc":      usc_resp,
                }, ensure_ascii=False) + "\n")

    print("[retry] Done — re-exporting CSVs")
    # Re-export after retry
    records = []
    with open(CHECKPOINT_PATH, encoding="utf-8") as f:
        for line in f:
            if line.strip():
                try: records.append(json.loads(line))
                except: pass
    records.sort(key=lambda r: (r["id"] is None, r["id"]))
    write_submission(records, "response_majority",
                     os.path.join(RESULTS_DIR, "submission_majority.csv"))
    write_submission(records, "response_weighted",
                     os.path.join(RESULTS_DIR, "submission_weighted.csv"))
    write_submission(records, "response_usc",
                     os.path.join(RESULTS_DIR, "submission_usc.csv"))

run_retry()

# ── Section 10 – Zip & Upload to Drive ───────────────────────────────────────

!cd /content && zip -rq 151B_SP26_Competition_done_dsft.zip 151B_SP26_Competition \
    -x "151B_SP26_Competition/__pycache__/*" \
       "151B_SP26_Competition/.ipynb_checkpoints/*"

!cp /content/151B_SP26_Competition_done_dsft.zip "/content/drive/MyDrive/CSE 151B/"
!ls -lh "/content/drive/MyDrive/CSE 151B/151B_SP26_Competition_done_dsft.zip"





# import json
# import os
# import re
# import sys
# from pathlib import Path
# from typing import Optional
# import ninja
# from collections import Counter

# from transformers import AutoTokenizer
# from vllm import LLM, SamplingParams
# from tqdm import tqdm
# import sympy as sp
# from sympy.parsing.latex import parse_latex

# # ── Configuration ─────────────────────────────────────────────────────────────
# # MODEL_ID    = "/home/xuz037/.cache/huggingface/hub/models--Qwen--Qwen3-4B-Thinking-2507/snapshots/768f209d9ea81521153ed38c47d515654e938aea"
# MODEL_ID = "Qwen/Qwen3-4B-Thinking-2507"
# GPU_ID      = "0"                    # CUDA_VISIBLE_DEVICES
# DATA_PATH   = "data/private.jsonl"    # Changed to private test set
# # OUTPUT_PATH = "results/submission.jsonl" # Changed to submission output
# OUTPUT_PATH = "/content/151B_SP26_Competition/results/submission.jsonl"
# MAX_TOKENS  = 32768
# N_SAMPLES   = 5                      # 5 samples for majority voting
# CHUNK_SIZE  = 2                     # <--- NEW: Process and save 50 questions at a time

# os.environ["CUDA_VISIBLE_DEVICES"] = GPU_ID
# os.environ["VLLM_USE_FLASHINFER_SAMPLER"] = "0"
# # os.environ["PATH"] = ninja.BIN_DIR + ":" + os.environ.get("PATH", "")
# # os.environ["LIBRARY_PATH"] = "/opt/conda/lib:" + os.environ.get("LIBRARY_PATH", "")
# # os.environ["LD_LIBRARY_PATH"] = "/opt/conda/lib:" + os.environ.get("LD_LIBRARY_PATH", "")
# # os.environ["TRANSFORMERS_OFFLINE"] = "1"
# # os.environ["HF_DATASETS_OFFLINE"] = "1"

# data = [json.loads(line) for line in open(DATA_PATH)]

# n_mcq  = sum(bool(d.get("options")) for d in data)
# n_free = sum(not d.get("options")   for d in data)
# print(f"Loaded {len(data)} questions  ({n_mcq} MCQ, {n_free} free-form)")

# # Preview one MCQ and one free-form item
# mcq_sample  = next(d for d in data if d.get("options"))
# free_sample = next(d for d in data if not d.get("options"))

# print("\n── MCQ sample ──")
# print(json.dumps(mcq_sample, indent=2))
# print("\n── Free-form sample ──")
# print(json.dumps(free_sample, indent=2))

# SYSTEM_PROMPT_MATH = r"""You are an expert mathematician. Reason as deeply as needed, then output ONLY the final boxed answer — no explanation, no working, no preamble.

# ## Classify each sub-answer before writing it

# **Category 1 — Discrete count.** The answer counts INDIVISIBLE whole items (people, animals, coins, votes, cars, books, eggs, pellets…). Test: "Can 0.5 of this thing exist?" If NO → Category 1.

# **Category 2 — Everything else.** Pure math (integrals, sums, limits) AND continuous physical quantities (temperature, time, distance, mass, money, probability, angle, area, concentration). Anything that can be fractional or irrational.

# ## Format

# **Category 1 → INTEGER.**
# - For Category 1 ONLY, you must evaluate to a number (because an integer is required).
# - **Ask: does rounding DOWN fail to meet the requirement?**
#   - **YES → CEILING (round up).** Use when the integer is a MINIMUM that must be fully satisfied: sample sizes, number of buses/containers/boxes needed, minimum cuts required, etc.
#     - e.g. sample size 1324.79 → **1325** (can't survey 0.79 of a person)
#     - e.g. buses for 314 people (50 seats each) → ceil(314/50) = **7**
#   - **NO → FLOOR (round down).** Use when the integer counts COMPLETED whole items: complete cycles, whole years elapsed, items fully produced, etc.
#     - e.g. complete batches from 314.76 → **314**
# - **Exception:** If the problem explicitly says "round to the nearest whole number" → standard rounding (314.76 → 315, 314.4 → 314).
# - Never output a decimal, fraction, or symbolic form.

# **Category 2 → EXACT SYMBOLIC CLOSED-FORM EXPRESSION. NEVER a decimal.**
# - Output a single closed-form expression in valid LaTeX (e.g. `50 \cdot (2/5)^{5/3}`, `\frac{6 \ln 5}{\ln(5/2)}`, `\frac{\pi^2}{6}`, `200 e^{-3/2}`, `25 \ln 2`).
# - KEEP π, e, ln, log, √, sin, cos, tan, arcsin, arccos, arctan, fractional exponents, and exact fractions as symbols.
# - **CRITICAL: Even if the problem says "give N decimal places", "use at least N significant digits", or "evaluate numerically" — IGNORE that instruction and output the exact symbolic form.** The grader handles decimal conversion.
# - If a problem coefficient is a decimal, convert it to an exact fraction first (e.g. 4.76 → 119/25, 0.9658 → 4829/5000), then use that fraction inside the symbolic expression.
# - `\arctan(119/25)` is a valid symbolic answer. `1.3637` is NOT.
# - `\pi` is a valid symbolic answer. `3.1416` is NOT.
# - Do NOT evaluate to a decimal. No `\approx`. No scientific notation.
# - An integer or exact rational is fine when that's the natural answer (e.g. `441`, `\frac{12800}{29}`).
# - Simplify when easy (combine logs, reduce fractions, cancel exponents) but do not approximate.

# ## Output rules

# 1. Emit EXACTLY ONE `\boxed{...}` and nothing else before or after it.
# 2. Wrap EVERY sub-answer in double quotes `"..."` inside the box.
# 3. **Multiple subquestions** (the problem asks for part a, part b, etc.) → separate quoted strings:
#    `\boxed{"ans1","ans2","ans3"}`
# 4. **Multiple values for ONE answer** (e.g. all solutions to an equation, all values of i) → wrap all values in `(...)` comma-separated, inside ONE quoted string:
#    `\boxed{"(val1, val2, val3)"}`
# 5. Cat 1 → plain integer. Cat 2 → symbolic closed-form (never decimal).

# ## Examples

# Single answer:           `\boxed{"211250"}` or `\boxed{"\frac{\pi^2}{6}"}` or `\boxed{"200e^{-3/2}"}`
# Interval answer:         `\boxed{"(-8,\infty)"}`
# Multiple solutions:      `\boxed{"(0, -\frac{11}{8})"}` or `\boxed{"(\frac{1}{3}, -2)"}`
# Multiple values of i:    `\boxed{"(2^{-1/8}-1, -2^{-1/8}+1)"}`
# Multi-subquestion:       `\boxed{"\arctan(123/31)","e^2"}` or `\boxed{"(50(2/5)^{5/3},50(2/13)^{4/3})","\frac{6\ln5}{\ln(5/2)}"}`
# Multi-select MCQ:        `\boxed{"B, C, E, G"}`
# Single letter MCQ:       `\boxed{"C"}`
# """

# SYSTEM_PROMPT_MCQ = (
#     "You are an expert mathematician. Reason as deeply as needed"
#     "CRITICAL: Your ENTIRE response must be exactly one token: \\boxed{X} where X is the correct letter."
#     " No explanation. No working. No preamble. Just \\boxed{X}."
#     " Example of a complete valid response: \\boxed{C}"
#     " If your computed answer matches no option, pick the closest. Still output only \\boxed{X}."
# )


# def build_prompt(question: str, options: Optional[list]) -> tuple[str, str]:
#     """Return (system_prompt, user_prompt) for a question."""
#     if options:
#         labels    = [chr(65 + i) for i in range(len(options))]
#         opts_text = "\n".join(f"{lbl}. {opt.strip()}" for lbl, opt in zip(labels, options))
#         return SYSTEM_PROMPT_MCQ, f"{question}\n\nOptions:\n{opts_text}"
#     return SYSTEM_PROMPT_MATH, question


# # Verify with samples
# for label, item in [("MCQ", mcq_sample), ("Free-form", free_sample)]:
#     sys_p, usr_p = build_prompt(item["question"], item.get("options"))
#     print(f"── {label} user prompt (first 200 chars) ──")
#     print(usr_p[:200], "...\n")

# # tokenizer = AutoTokenizer.from_pretrained(MODEL_ID)
# # tokenizer.pad_token = tokenizer.eos_token



# # llm = LLM(
# #     model=MODEL_ID,
# #     quantization="bitsandbytes",
# #     load_format="bitsandbytes",
# #     enable_prefix_caching=False,
# #     gpu_memory_utilization=0.70,
# #     max_model_len=13000,
# #     trust_remote_code=True,
# #     max_num_seqs=64,
# #     max_num_batched_tokens=13000,
# # )

# # sampling_params = SamplingParams(
# #     max_tokens=MAX_TOKENS,
# #     temperature=0.6,
# #     top_p=0.95,
# #     top_k=20,
# #     min_p=0.0,
# #     presence_penalty=0.0,
# #     repetition_penalty=1.0,
# #     n=N_SAMPLES,
# # )

# # print("Model loaded.")

# tokenizer = AutoTokenizer.from_pretrained(MODEL_ID)
# tokenizer.pad_token = tokenizer.eos_token



# # llm = LLM(
# #     model=MODEL_ID,
# #     quantization="bitsandbytes",
# #     load_format="bitsandbytes",
# #     enable_prefix_caching=False,
# #     gpu_memory_utilization=0.60,
# #     max_model_len=32768,
# #     trust_remote_code=True,
# #     max_num_seqs=256,
# #     max_num_batched_tokens=32768,
# # )
# import sys
# sys.stdout.fileno = lambda: 1
# sys.stderr.fileno = lambda: 2
# llm = LLM(
#     model=MODEL_ID,
#     # quantization="bitsandbytes",
#     # load_format="bitsandbytes",
#     enable_prefix_caching=False,
#     gpu_memory_utilization=0.60,
#     # max_model_len=16384,
#     max_model_len=32768,
#     trust_remote_code=True,
#     max_num_seqs=256,
#     max_num_batched_tokens=32768,
#     # enable_lora=True,
#     # max_lora_rank=32,           # must match your r=32
#     # max_loras=1,
#     # enforce_eager=True # Added this line
# )

# sampling_params = SamplingParams(
#     max_tokens=MAX_TOKENS,
#     temperature=0.85,
#     top_p=0.95,
#     top_k=20,
#     min_p=0.0,
#     presence_penalty=0.0,
#     repetition_penalty=1.0,
#     n=N_SAMPLES,
# )

# print("Model loaded.")

# # ============================================================================
# # HELPER FUNCTIONS: Numerify & Majority Vote
# # ============================================================================
# N_DIGITS = 10
# WORK_PREC = N_DIGITS + 6

# def find_last_boxed_span(text: str):
#     if not text: return None
#     needle = r"\boxed"
#     n, last, i = len(text), None, 0
#     while True:
#         idx = text.find(needle, i)
#         if idx ==  -1: break
#         j = idx + len(needle)
#         while j < n and text[j].isspace(): j += 1
#         if j >= n or text[j] != "{":
#             i = idx + len(needle)
#             continue
#         depth, k = 1, j + 1
#         start_content = k
#         while k < n and depth > 0:
#             ch = text[k]
#             if ch == "\\" and k + 1 < n:
#                 k += 2; continue
#             if ch == "{": depth += 1
#             elif ch == "}":
#                 depth -= 1
#                 if depth == 0: break
#             k += 1
#         if depth == 0:
#             last = (idx, k + 1, text[start_content:k])
#             i = k + 1
#         else: i = idx + len(needle)
#     return last

# def split_top_level_commas(s: str):
#     """Split on commas NOT inside any brace or paren level.
#     Tracks both {} and () so \left(...,...\right) is kept intact."""
#     out, depth, start, i, n = [], 0, 0, 0, len(s)
#     while i < n:
#         ch = s[i]
#         if ch == "\\" and i + 1 < n:
#             i += 2
#             continue
#         if ch in "{(":
#             depth += 1
#         elif ch in "})":
#             depth -= 1
#         elif ch == "," and depth == 0:
#             out.append(s[start:i])
#             start = i + 1
#         i += 1
#     out.append(s[start:])
#     return [p.strip() for p in out if p.strip() != ""]

# # Regex substitutions applied before feeding LaTeX to sympy.
# _CLEANUPS = [
#     (r"\\dfrac",               r"\\frac"),
#     (r"\\tfrac",               r"\\frac"),
#     (r"\\!",                   ""),
#     (r"\\,",                   ""),
#     (r"\\;",                   ""),
#     (r"\\ ",                   ""),
#     (r"\\\\ ",                 " "),
#     (r"\\left",                ""),
#     (r"\\right",               ""),
#     (r"\\$",                   ""),
#     (r"\\%",                   ""),           # \% → strip (value already IS the percentage)
#     (r"\\text\{([^}]*)\}",     r"\1"),        # \text{C} → C
# ]

# def _clean_latex(s: str) -> str:
#     """Apply _CLEANUPS and convert degree notation to radian decimals."""
#     s = s.strip()
#     # Convert degree notation to a radian decimal wrapped in braces.
#     # \tan 23^\circ → \tan {0.40142...}   (braces = grouped argument)
#     # 67°           → {1.16937...}
#     def _deg2rad(m):
#         return "{" + str(_math.radians(float(m.group(1)))) + "}"
#     # (?(2)\}) = closing brace only if group 2 captured the opening brace.
#     # Prevents eating the '}' that closes a surrounding \frac{}{...} argument.
#     s = re.sub(r"(\d+(?:\.\d+)?)\s*\^(\{)?\\circ(?(2)\})", _deg2rad, s)
#     s = re.sub(r"(\d+(?:\.\d+)?)\s*°",                      _deg2rad, s)
#     for pat, rep in _CLEANUPS:
#         s = re.sub(pat, rep, s)
#     return re.sub(r"^=\s*", "", s).strip()

# def _format_numeric(val, n_digits: int) -> str:
#     """Format a sympy numeric value as a decimal string.
#     Handles real, complex, and infinite results."""
#     re_part, im_part = val.as_real_imag()
#     re_f = float(re_part)
#     im_f = float(im_part)
#     if _math.isinf(re_f):
#         return "\\infty" if re_f > 0 else "-\\infty"
#     if abs(im_f) < 1e-12:
#         return f"{re_f:.{n_digits}f}"
#     sign = "+" if im_f >= 0 else ""
#     return f"{re_f:.{n_digits}f}{sign}{im_f:.{n_digits}f}i"

# def _sub_stat_quantiles(s: str) -> str:
#     """Pre-substitute statistical quantiles with decimal values before parse_latex.

#     Handles z_{α}, chi^2_{α,df}, t_{α,df}, t_{α,\frac{num}{den}}, F_{α,df1,df2}.
#     Requires scipy; silently skips if not installed.
#     """
#     try:
#         from scipy import stats as _sc

#         def _z(m):
#             return str(_sc.norm.ppf(1 - float(m.group(1))))
#         s = re.sub(r"\bz\s*_\{?\s*([0-9.]+)\s*\}?", _z, s)

#         def _chi2(m):
#             return str(_sc.chi2.ppf(1 - float(m.group(1)), int(m.group(2))))
#         s = re.sub(
#             r"\\?chi\^?2\s*_\{?\s*([0-9.]+)\s*,\s*([0-9]+)\s*\}?",
#             _chi2, s, flags=re.IGNORECASE,
#         )

#         # t with fractional df: t_{alpha, \frac{num}{den}}
#         def _t_frac(m):
#             return str(_sc.t.ppf(1 - float(m.group(1)), float(m.group(2)) / float(m.group(3))))
#         s = re.sub(
#             r"\bt\s*_\{?\s*([0-9.]+)\s*,\s*\\frac\{([0-9]+)\}\{([0-9]+)\}\s*\}?",
#             _t_frac, s,
#         )

#         def _t(m):
#             return str(_sc.t.ppf(1 - float(m.group(1)), float(m.group(2))))
#         s = re.sub(r"\bt\s*_\{?\s*([0-9.]+)\s*,\s*([0-9.]+)\s*\}?", _t, s)

#         def _f(m):
#             return str(_sc.f.ppf(1 - float(m.group(1)), int(m.group(2)), int(m.group(3))))
#         s = re.sub(
#             r"\bF\s*_\{?\s*([0-9.]+)\s*,\s*([0-9]+)\s*,\s*([0-9]+)\s*\}?", _f, s
#         )
#     except ImportError:
#         pass
#     return s

# def _eval_cdf_expression(s: str, n_digits: int, _depth: int = 0):
#     r"""Evaluate \Phi(x), \Phi^{-1}(p), \Pr(T_n < x).
#     Returns decimal string, or None if no CDF pattern found."""
#     if "\\Phi" not in s and "\\Pr" not in s:
#         return None
#     try:
#         from scipy import stats as _sc

#         def _inner(expr_str):
#             if _depth >= 2:
#                 return None
#             result = evaluate_piece(expr_str.strip(), n_digits, _depth + 1)
#             try:
#                 return float(result)
#             except (ValueError, TypeError):
#                 return None

#         s_work = s

#         def _phi_inv(m):
#             v = _inner(m.group(1))
#             return f"{_sc.norm.ppf(v):.{n_digits}f}" if v is not None else m.group(0)
#         s_work = re.sub(r"\\Phi\s*\^\{-1\}\s*\(([^)]+)\)", _phi_inv, s_work)

#         def _phi(m):
#             v = _inner(m.group(1))
#             return f"{_sc.norm.cdf(v):.{n_digits}f}" if v is not None else m.group(0)
#         s_work = re.sub(r"\\Phi\s*\(([^)]+)\)", _phi, s_work)

#         def _pr_t(m):
#             df_v = _inner(m.group(1))
#             x_v  = _inner(m.group(2))
#             if df_v is None or x_v is None:
#                 return m.group(0)
#             return f"{_sc.t.cdf(x_v, df_v):.{n_digits}f}"
#         s_work = re.sub(r"\\Pr\s*\(\s*T_\{?(\d+)\}?\s*<\s*([^)]+)\)", _pr_t, s_work)

#         if s_work == s:
#             return None

#         try:
#             return f"{float(s_work):.{n_digits}f}"
#         except ValueError:
#             pass
#         try:
#             val = sp.N(sp.sympify(s_work), WORK_PREC)
#             return _format_numeric(val, n_digits)
#         except Exception:
#             pass
#         return s_work

#     except Exception:
#         return None

# def evaluate_piece(piece: str, n_digits: int = N_DIGITS, _depth: int = 0) -> str:
#     """Convert a single boxed sub-answer to an N-digit decimal string."""
#     p = (piece or "").strip()
#     if not p:
#         return p
#     # Single capital letter → always an MCQ choice, never a math expression.
#     # Must come before sympy parsing (sympy maps E → Euler's constant).
#     if re.fullmatch(r"[A-Z]", p):
#         return p
#     if re.fullmatch(r"-?\d+", p):
#         return p
#     m = re.fullmatch(r"-?\d+\.\d+", p)
#     if m:
#         try:
#             return f"{float(p):.{n_digits}f}"
#         except Exception:
#             pass

#     s = _clean_latex(p)
#     # Post-clean letter check: \text{C} → C after cleaning
#     if re.fullmatch(r"[A-Z]+", s):
#         return s

#     s = _sub_stat_quantiles(s)

#     cdf_result = _eval_cdf_expression(s, n_digits, _depth)
#     if cdf_result is not None:
#         return cdf_result

#     try:
#         if parse_latex is None:
#             raise RuntimeError("no latex parser")
#         expr = parse_latex(s)
#         # Equality like x = -1/2 → extract RHS
#         if isinstance(expr, sp.Eq):
#             expr = expr.rhs
#         expr = expr.subs([
#             (sp.Symbol('pi'), sp.pi),
#             (sp.Symbol('e'),  sp.E),
#             (sp.Symbol('i'),  sp.I),
#         ])
#         val = sp.N(expr, WORK_PREC)
#         return _format_numeric(val, n_digits)
#     except Exception as e:
#         print(f"[parse_latex FAILED] input={s!r}  error={e}")

#     try:
#         fallback_s = s.replace("\\", "")
#         expr = sp.sympify(fallback_s)
#         val  = sp.N(expr, WORK_PREC)
#         return _format_numeric(val, n_digits)
#     except Exception as e:
#         print(f"[sympify FAILED] input={fallback_s!r}  error={e}")

#     # Scipy fallback for standalone statistical quantiles
#     try:
#         from scipy import stats as _sc

#         m = re.search(r"chi\^?2\s*_\{?\s*([0-9.]+)\s*,\s*([0-9]+)\s*\}?", p, re.IGNORECASE)
#         if m:
#             return f"{_sc.chi2.ppf(1 - float(m.group(1)), int(m.group(2))):.{n_digits}f}"

#         m = re.search(r"[Ff]\s*_\{?\s*([0-9.]+)\s*,\s*([0-9]+)\s*,\s*([0-9]+)\s*\}?", p)
#         if m:
#             return f"{_sc.f.ppf(1 - float(m.group(1)), int(m.group(2)), int(m.group(3))):.{n_digits}f}"

#         m = re.search(r"\bt\s*_\{?\s*([0-9.]+)\s*,\s*([0-9]+)\s*\}?", p)
#         if m:
#             return f"{_sc.t.ppf(1 - float(m.group(1)), float(m.group(2))):.{n_digits}f}"

#         m = re.search(r"\bz\s*_\{?\s*([0-9.]+)\s*\}?", p)
#         if m:
#             return f"{_sc.norm.ppf(1 - float(m.group(1))):.{n_digits}f}"

#     except Exception as e:
#         print(f"[scipy FAILED] input={p!r}  error={e}")

#     return p

# # def numerify_response(text: str, n_digits: int = N_DIGITS) -> str:
# #     span = find_last_boxed_span(text)
# #     if span is None: return text
# #     start, end, content = span
# #     parts = split_top_level_commas(content)
# #     first_part = evaluate_piece(parts[0], n_digits)
# #     new_box = "\\boxed{" + first_part + "}"
# #     return text[:start] + new_box + text[end:]
# def numerify_paren_list(s: str, n_digits: int = N_DIGITS) -> str:
#     """Numerify a sub-answer that may be a parenthesised value list.
#     Handles both bare '(val1, val2)' and '\left(val1, val2\right)'."""
#     inner = s.strip()
#     unwrapped = re.sub(r"\\left\s*", "", inner)
#     unwrapped = re.sub(r"\\right\s*", "", unwrapped).strip()
#     if unwrapped.startswith('(') and unwrapped.endswith(')'):
#         inner_content = unwrapped[1:-1]
#         parts = split_top_level_commas(inner_content)
#         if len(parts) > 1:
#             new_parts = [evaluate_piece(p, n_digits) for p in parts]
#             return '(' + ', '.join(new_parts) + ')'
#     return evaluate_piece(s, n_digits)


# def numerify_response(text: str, n_digits: int = N_DIGITS) -> str:
#     """Replace the content of the LAST \\boxed{} with numerically evaluated parts.

#     Supports two formats:
#     - Quoted (new):  \\boxed{"ans1","ans2"} — each sub-answer in double quotes.
#     - Legacy:        \\boxed{a, b, c} — bare comma-separated sub-answers.
#     """
#     try:
#         span = find_last_boxed_span(text)
#         if span is None:
#             return text
#         start, end, content = span

#         # Quoted format: \boxed{"ans1","ans2"}
#         quoted_parts = split_quoted_answers(content)
#         if quoted_parts is not None:
#             new_parts = []
#             for p in quoted_parts:
#                 p = compress_letter_list(p)
#                 p = numerify_paren_list(p, n_digits)
#                 new_parts.append(p)
#             new_box = "\\boxed{" + ",".join(f'"{p}"' for p in new_parts) + "}"
#             return text[:start] + new_box + text[end:]

#         # Legacy: bare comma-separated (or single \left(...\right) interval)
#         parts = split_top_level_commas(content)
#         if not parts:
#             return text
#         new_parts = [numerify_paren_list(p, n_digits) for p in parts]
#         new_box = "\\boxed{" + ", ".join(new_parts) + "}"
#         return text[:start] + new_box + text[end:]
#     except Exception:
#         return text

# def extract_letter(text: str) -> str:
#     m = re.search(r"\\boxed\{([A-Za-z])\}", text or "")
#     if m:
#         return m.group(1).upper()
#     matches = re.findall(r"\b([A-Z])\b", (text or "").upper())
#     return matches[-1] if matches else ""


# def extract_boxed(text: str) -> str:
#     span = find_last_boxed_span(text or "")
#     return span[2] if span else ""


# def canonical(boxed_str: str) -> str:
#     if not boxed_str:
#         return ""
#     try:
#         s = boxed_str.replace("\\dfrac", "\\frac").replace("$", "").strip()
#         return str(sp.simplify(parse_latex(s)))
#     except Exception:
#         return boxed_str.replace("\\dfrac", "\\frac").replace(" ", "").strip()

# def majority_vote_free(response_list):
#     canon_to_full = {}
#     votes = []
#     for r in response_list:
#         b = extract_boxed(r)
#         if not b:
#             continue
#         c = canonical(b)
#         if c not in canon_to_full:
#             canon_to_full[c] = r
#         votes.append(c)
#     if not votes:
#         return response_list[0] if response_list else ""
#     winner = Counter(votes).most_common(1)[0][0]
#     return canon_to_full[winner]


# def majority_vote_mcq(response_list):
#     letter_to_full = {}
#     votes = []
#     for r in response_list:
#         v = extract_letter(r)
#         if v:
#             if v not in letter_to_full:
#                 letter_to_full[v] = r
#             votes.append(v)
#     if not votes:
#         return response_list[0] if response_list else ""
#     winner = Counter(votes).most_common(1)[0][0]
#     return letter_to_full[winner]

# # ============================================================================
# # CHUNKING, GENERATION, AND SAVING LOOP
# # ============================================================================

# # 1. Check for existing progress (Checkpointing)
# completed_ids = set()
# if os.path.exists(OUTPUT_PATH):
#     with open(OUTPUT_PATH, "r", encoding="utf-8") as f:
#         for line in f:
#             if line.strip():
#                 try:
#                     record = json.loads(line)
#                     if "id" in record:
#                         completed_ids.add(str(record["id"]))
#                 except json.JSONDecodeError:
#                     pass

# print(f"Found {len(completed_ids)} already completed records in {OUTPUT_PATH}.")

# # 2. Filter data
# remaining_data = [item for item in data if str(item.get("id")) not in completed_ids]
# print(f"Remaining records to process: {len(remaining_data)}")

# if len(remaining_data) == 0:
#     print("All records processed. Ready for Kaggle submission!")
# else:
#     # Ensure output directory exists
#     os.makedirs(os.path.dirname(OUTPUT_PATH) if os.path.dirname(OUTPUT_PATH) else ".", exist_ok=True)

#     num_chunks = (len(remaining_data) + CHUNK_SIZE - 1) // CHUNK_SIZE

#     for chunk_idx in range(num_chunks):
#         start_idx = chunk_idx * CHUNK_SIZE
#         end_idx = min(start_idx + CHUNK_SIZE, len(remaining_data))
#         chunk_data = remaining_data[start_idx:end_idx]

#         print(f"\n--- Processing Chunk {chunk_idx + 1}/{num_chunks} (Items {start_idx+1} to {end_idx}) ---")

#         # A. Build Prompts
#         prompts = []
#         for item in chunk_data:
#             system, user = build_prompt(item["question"], item.get("options"))
#             prompt_text = tokenizer.apply_chat_template(
#                 [{"role": "system", "content": system},
#                  {"role": "user",   "content": user}],
#                 tokenize=False,
#                 add_generation_prompt=True,
#                 enable_thinking=True, # Essential for Qwen3-Thinking
#             )
#             prompts.append(prompt_text)

#         # B. Generate Responses
#         outputs = llm.generate(prompts, sampling_params=sampling_params)
#         raw_responses = [[o.text.strip() for o in out.outputs] for out in outputs]

#         # C. Post-Process (Numerify)
#         responses_changed = [
#             [numerify_response(sample) for sample in sample_list]
#             for sample_list in raw_responses
#         ]

#         # D. Majority Vote
#         final_responses = []
#         for item, response_list in zip(chunk_data, responses_changed):
#             is_mcq = bool(item.get("options"))
#             if is_mcq:
#                 pred_full = majority_vote_mcq(response_list)
#             else:
#                 pred_full = majority_vote_free(response_list)
#             final_responses.append(pred_full)

#         # E. Save Chunk Immediately (Append Mode)
#         with open(OUTPUT_PATH, "a", encoding="utf-8") as f:
#             for item, final_resp in zip(chunk_data, final_responses):
#                 record = {
#                     "id": item.get("id"),
#                     "is_mcq": bool(item.get("options")),
#                     "response": final_resp
#                 }
#                 f.write(json.dumps(record) + "\n")
#         print(f"Chunk {chunk_idx + 1} saved successfully.")

#     print("\nAll processing complete! Your file is ready for Kaggle.")

# # fix_boxed.py
# import json
# import re
# import shutil
# from pathlib import Path

# INPUT_PATH  = Path("results/submission.jsonl")
# OUTPUT_PATH = Path("results/submission_fixed.jsonl")
# BACKUP_PATH = Path("results/submission.jsonl.bak")

# # Matches the LAST "boxed{...}" in the text, even if the leading "\b" is missing.
# # Captures: optional backslash, optional 'b', then 'oxed{...}'
# # Examples it catches:
# #   \boxed{E}      ✓ (already correct — left as-is)
# #   oxed{E}        ✓ (missing \b)
# #   boxed{E}       ✓ (missing backslash)
# #   \boxed{\frac{1}{2}}  ✓ (with nested braces — handled by balanced matcher)
# BOXED_TOKEN_RE = re.compile(r"(\\?)b?oxed\s*\{", re.IGNORECASE)


# def find_last_balanced_boxed(text: str):
#     """Return (start, end, inner) for the last boxed{...} span with balanced braces."""
#     last = None
#     for m in BOXED_TOKEN_RE.finditer(text):
#         # require it to actually contain "oxed{"
#         if "oxed{" not in text[m.start():m.end() + 1].replace(" ", ""):
#             continue
#         brace_open = m.end() - 1   # position of '{'
#         depth, i, n = 1, brace_open + 1, len(text)
#         while i < n and depth > 0:
#             ch = text[i]
#             if ch == "\\" and i + 1 < n:
#                 i += 2
#                 continue
#             if ch == "{":
#                 depth += 1
#             elif ch == "}":
#                 depth -= 1
#                 if depth == 0:
#                     break
#             i += 1
#         if depth == 0:
#             last = (m.start(), i + 1, text[brace_open + 1:i])
#     return last


# def normalize_final_box(text: str) -> tuple[str, bool]:
#     """Rewrite the LAST boxed-like answer as \\boxed{...}. Returns (new_text, changed)."""
#     span = find_last_balanced_boxed(text)
#     if span is None:
#         return text, False
#     start, end, inner = span
#     correct = "\\boxed{" + inner + "}"
#     if text[start:end] == correct:
#         return text, False
#     return text[:start] + correct + text[end:], True


# def main():
#     if not INPUT_PATH.exists():
#         raise SystemExit(f"Not found: {INPUT_PATH}")

#     shutil.copy2(INPUT_PATH, BACKUP_PATH)
#     print(f"Backup written to {BACKUP_PATH}")

#     n_total = n_fixed = n_missing = 0
#     with INPUT_PATH.open("r", encoding="utf-8") as fin, \
#          OUTPUT_PATH.open("w", encoding="utf-8") as fout:
#         for line in fin:
#             if not line.strip():
#                 continue
#             rec = json.loads(line)
#             n_total += 1
#             resp = rec.get("response", "")
#             new_resp, changed = normalize_final_box(resp)
#             if changed:
#                 n_fixed += 1
#                 print(f"[fixed] id={rec.get('id')}")
#             if find_last_balanced_boxed(new_resp) is None:
#                 n_missing += 1
#                 print(f"[WARN ] id={rec.get('id')} — no boxed answer found at all")
#             rec["response"] = new_resp
#             fout.write(json.dumps(rec, ensure_ascii=False) + "\n")

#     print(f"\nProcessed {n_total} records: fixed {n_fixed}, no-box {n_missing}")
#     print(f"Wrote {OUTPUT_PATH}")
#     print(f"Original kept as {BACKUP_PATH}")


# if __name__ == "__main__":
#     main()

# # fix_boxed.py
# import csv
# import json
# import re
# import shutil
# from pathlib import Path

# INPUT_PATH   = Path("results/submission.jsonl")
# OUTPUT_JSONL = Path("results/submission_fixed.jsonl")
# OUTPUT_CSV   = Path("results/submission.csv")
# BACKUP_PATH  = Path("results/submission.jsonl.bak")

# BOXED_TOKEN_RE = re.compile(r"\\?b?oxed\s*\{", re.IGNORECASE)


# def find_last_balanced_boxed(text: str):
#     """Return (start, end, inner) for the last boxed{...} span with balanced braces."""
#     last = None
#     for m in BOXED_TOKEN_RE.finditer(text):
#         token = text[m.start():m.end()]
#         if "oxed{" not in token.replace(" ", ""):
#             continue
#         brace_open = m.end() - 1
#         depth, i, n = 1, brace_open + 1, len(text)
#         while i < n and depth > 0:
#             ch = text[i]
#             if ch == "\\" and i + 1 < n:
#                 i += 2
#                 continue
#             if ch == "{":
#                 depth += 1
#             elif ch == "}":
#                 depth -= 1
#                 if depth == 0:
#                     break
#             i += 1
#         if depth == 0:
#             last = (m.start(), i + 1, text[brace_open + 1:i])
#     return last


# def normalize_final_box(text: str) -> tuple[str, bool]:
#     span = find_last_balanced_boxed(text)
#     if span is None:
#         return text, False
#     start, end, inner = span
#     correct = "\\boxed{" + inner + "}"
#     if text[start:end] == correct:
#         return text, False
#     return text[:start] + correct + text[end:], True


# def main():
#     if not INPUT_PATH.exists():
#         raise SystemExit(f"Not found: {INPUT_PATH}")

#     shutil.copy2(INPUT_PATH, BACKUP_PATH)
#     print(f"Backup written to {BACKUP_PATH}")

#     n_total = n_fixed = n_missing = 0
#     rows = []

#     with INPUT_PATH.open("r", encoding="utf-8") as fin, \
#          OUTPUT_JSONL.open("w", encoding="utf-8") as fjsonl:
#         for line in fin:
#             if not line.strip():
#                 continue
#             rec = json.loads(line)
#             n_total += 1
#             resp = rec.get("response", "")
#             new_resp, changed = normalize_final_box(resp)
#             if changed:
#                 n_fixed += 1
#                 print(f"[fixed] id={rec.get('id')}")
#             if find_last_balanced_boxed(new_resp) is None:
#                 n_missing += 1
#                 print(f"[WARN ] id={rec.get('id')} — no boxed answer found")
#             rec["response"] = new_resp
#             fjsonl.write(json.dumps(rec, ensure_ascii=False) + "\n")
#             rows.append((rec.get("id"), new_resp))

#     rows.sort(key=lambda r: (r[0] is None, r[0]))

#     with OUTPUT_CSV.open("w", encoding="utf-8", newline="") as fcsv:
#         writer = csv.writer(fcsv, quoting=csv.QUOTE_MINIMAL)
#         writer.writerow(["id", "response"])
#         for rid, resp in rows:
#             writer.writerow([rid, resp])

#     print(f"\nProcessed {n_total} records: fixed {n_fixed}, no-box {n_missing}")
#     print(f"Wrote {OUTPUT_JSONL}")
#     print(f"Wrote {OUTPUT_CSV}")
#     print(f"Original kept as {BACKUP_PATH}")


# if __name__ == "__main__":
#     main()

# # ============================================================================
# # RETRY: delete truncated rows from submission.jsonl, then re-run anything
# # that's still missing (truncated OR never-generated). Numerify during, then
# # normalize any "boxed{...}" -> "\boxed{...}" via fix_boxed main(), and finally
# # report any IDs still without a boxed answer.
# # ============================================================================
# import gc
# import torch
# import shutil as _shutil
# import sys
# sys.stdout.fileno = lambda: 1
# sys.stderr.fileno = lambda: 2

# RETRY_BACKUP_PATH   = "/content/151B_SP26_Competition/results/submission.jsonl.before_retry"
# RETRY_MAX_MODEL_LEN = 65536   # was 32768 — doubled
# RETRY_MAX_TOKENS    = 60000   # was 32768 — give thinking room to finish
# RETRY_N_SAMPLES     = 5       # majority voting

# # --- 1. Back up the current submission ---
# _shutil.copy2(OUTPUT_PATH, RETRY_BACKUP_PATH)
# print(f"[retry] backup -> {RETRY_BACKUP_PATH}")

# # --- 2. DELETE: rewrite submission.jsonl with only records that have a box ---
# _kept = []
# with open(OUTPUT_PATH, "r", encoding="utf-8") as _f:
#     for _line in _f:
#         if not _line.strip():
#             continue
#         _rec = json.loads(_line)
#         if find_last_balanced_boxed(_rec.get("response", "")) is not None:
#             _kept.append(_rec)

# with open(OUTPUT_PATH, "w", encoding="utf-8") as _f:
#     for _rec in _kept:
#         _f.write(json.dumps(_rec) + "\n")

# print(f"[retry] After delete: submission.jsonl has {len(_kept)} good records")

# # --- 3. Compute missing = data IDs not present in submission.jsonl ---
# #     This catches both truncated (just deleted) AND never-generated records.
# _completed_ids = {str(_rec.get("id")) for _rec in _kept}
# _missing_data = [item for item in data if str(item.get("id")) not in _completed_ids]
# print(f"[retry] Missing IDs to retry: {len(_missing_data)}")
# print(f"[retry] First 30: {[item.get('id') for item in _missing_data[:30]]}")

# # --- 4. If anything's missing, rebuild LLM with bigger context and re-run ---
# if _missing_data:
#     try:
#         del llm
#     except NameError:
#         pass
#     gc.collect()
#     torch.cuda.empty_cache()
#     print(f"[retry] Released old LLM. Building new one with max_model_len={RETRY_MAX_MODEL_LEN}")
#     tokenizer = AutoTokenizer.from_pretrained(MODEL_ID)
#     tokenizer.pad_token = tokenizer.eos_token
#     llm = LLM(
#         model=MODEL_ID,
#         enable_prefix_caching=False,
#         gpu_memory_utilization=0.85,
#         max_model_len=RETRY_MAX_MODEL_LEN,
#         trust_remote_code=True,
#         max_num_seqs=64,
#         max_num_batched_tokens=RETRY_MAX_MODEL_LEN,
#         enforce_eager=True,
#     )

#     retry_sampling = SamplingParams(
#         max_tokens=RETRY_MAX_TOKENS,
#         temperature=0.85,
#         top_p=0.95,
#         top_k=20,
#         min_p=0.0,
#         presence_penalty=0.0,
#         repetition_penalty=1.0,
#         n=RETRY_N_SAMPLES,
#     )

#     _num_chunks = (len(_missing_data) + CHUNK_SIZE - 1) // CHUNK_SIZE
#     for _chunk_idx in range(_num_chunks):
#         _start = _chunk_idx * CHUNK_SIZE
#         _end   = min(_start + CHUNK_SIZE, len(_missing_data))
#         _chunk = _missing_data[_start:_end]
#         print(f"\n[retry chunk {_chunk_idx + 1}/{_num_chunks}] items {_start + 1}-{_end}")

#         _prompts = []
#         for _item in _chunk:
#             _sys_p, _usr_p = build_prompt(_item["question"], _item.get("options"))
#             _prompts.append(tokenizer.apply_chat_template(
#                 [{"role": "system", "content": _sys_p},
#                  {"role": "user",   "content": _usr_p}],
#                 tokenize=False,
#                 add_generation_prompt=True,
#                 enable_thinking=True,
#             ))

#         _outputs = llm.generate(_prompts, sampling_params=retry_sampling)
#         _raw = [[o.text.strip() for o in out.outputs] for out in _outputs]

#         # Numerify DURING retry (convert symbolic boxed expressions to decimals)
#         _processed = [[numerify_response(s) for s in lst] for lst in _raw]

#         with open(OUTPUT_PATH, "a", encoding="utf-8") as _f:
#             for _item, _samples in zip(_chunk, _processed):
#                 _is_mcq = bool(_item.get("options"))
#                 _pred = majority_vote_mcq(_samples) if _is_mcq else majority_vote_free(_samples)
#                 _f.write(json.dumps({
#                     "id": _item.get("id"),
#                     "is_mcq": _is_mcq,
#                     "response": _pred,
#                 }) + "\n")
#         print(f"[retry chunk {_chunk_idx + 1}] appended {len(_chunk)} records")

#     print("\n[retry] All retries complete.")
# else:
#     print("[retry] Nothing to retry — every data ID is already covered.")

# # --- 5. Normalize any incomplete boxes (e.g. "oxed{E}" -> "\boxed{E}") ---
# #     and regenerate submission_fixed.jsonl + submission.csv
# print("\n[retry] Running fix_boxed normalization + CSV generation")
# main()

# # --- 6. Final sanity check: any IDs still without a boxed answer? ---
# print("\n[retry] === Final check ===")
# _final_with_box = set()
# _final_without_box = []
# with open(OUTPUT_PATH, "r", encoding="utf-8") as _f:
#     for _line in _f:
#         if not _line.strip():
#             continue
#         _rec = json.loads(_line)
#         if find_last_balanced_boxed(_rec.get("response", "")) is not None:
#             _final_with_box.add(str(_rec.get("id")))
#         else:
#             _final_without_box.append(_rec.get("id"))

# _all_data_ids = {str(item.get("id")) for item in data}
# _never_generated = sorted(_all_data_ids - _final_with_box - {str(i) for i in _final_without_box})

# print(f"[retry] Total data records:           {len(_all_data_ids)}")
# print(f"[retry] Records with boxed answer:    {len(_final_with_box)}")
# print(f"[retry] Records present but no box:   {len(_final_without_box)}")
# print(f"[retry] Records never generated:      {len(_never_generated)}")
# if _final_without_box:
#     print(f"[retry] Still missing box (IDs): {_final_without_box[:30]}")
# if _never_generated:
#     print(f"[retry] Never generated (IDs):   {_never_generated[:30]}")
# if not _final_without_box and not _never_generated:
#     print("[retry] ✓ All records have a boxed answer. Ready for Kaggle.")

# # Zip the whole folder (excludes any HF cache that might've ended up inside)
# !cd /content && zip -rq 151B_SP26_Competition_done2.zip 151B_SP26_Competition \
#     -x "151B_SP26_Competition/__pycache__/*" \
#        "151B_SP26_Competition/.ipynb_checkpoints/*"

# # Copy zip to Drive

# # Verify
# !cp /content/151B_SP26_Competition_done2.zip /content/drive/MyDrive/CSE\ 151B/
# !ls -lh /content/drive/MyDrive/CSE\ 151B/151B_SP26_Competition_done2.zip

